### ISSUE TITLE
Failed to convert icon to .icns, skipping. Error: Icon conversion failed with status code 1.

### ISSUE THREAD

**Issue by zachriggle** [nativefier/nativefier#1183]
**Homework**

- [x] I looked at `nativefier --help` and https://github.com/nativefier/nativefier/blob/master/docs/api.md
- [x] I checked the [Troubleshooting section of the README](https://github.com/nativefier/nativefier/blob/master/README.md#troubleshooting).
- [x] I searched existing issues, open & closed. Yes, my bug is new.
- [x] I'm using the latest version available at https://github.com/nativefier/nativefier/releases

**Bug description**

When specifying `--icon icon.png`, an error message is displayed.  The image `icon.png` that I'm using is `https://images.vexels.com/media/users/3/137412/isolated/preview/1802b9d8ce3c819eebe90a86bbb61077-soundcloud-icon-logo-by-vexels.png` however this error occurs for ALL of the nativefier apps I've tried building.

```
Converting icons...
Converting icon icon.png to /var/folders/l1/f4rh7l7n0v59msb7psh91m7h0000gn/T/nativefier-16-24-42-iconconv--38040-5hk13qE37T06/icon.icns. Calling shell command: "/opt/brew/Cellar/nativefier/43.1.2/libexec/lib/node_modules/nativefier/icon-scripts/convertToIcns" "icon.png" "/var/folders/l1/f4rh7l7n0v59msb7psh91m7h0000gn/T/nativefier-16-24-42-iconconv--38040-5hk13qE37T06/icon.icns"
Failed to convert icon to .icns, skipping. Error: Icon conversion failed with status code 1.
stdout:
stderr: identify: UnableToOpenConfigureFile `delegates.xml' @ warning/configure.c/GetConfigureOptions/702.
identify: NoDecodeDelegateForThisImageFormat `PNG' @ error/constitute.c/ReadImage/572.
convert: UnableToOpenConfigureFile `delegates.xml' @ warning/configure.c/GetConfigureOptions/702.
convert: NoDecodeDelegateForThisImageFormat `PNG' @ error/constitute.c/ReadImage/572.
convert: NoImagesDefined `convert_temp/icon.png' @ error/convert.c/ConvertImageCommand/3322.
```

**Steps to reproduce**

Give your ***full*** nativefier command and its logs, with the ***`--verbose` flag***, on a ***public*** site:

<details><summary>Click to Expand: nativefier --verbose --single-instance ...</summary>

```
$ nativefier --verbose --single-instance --no-overwrite --bounce --darwin-dark-mode-support --user-agent 'Mozilla/5.0 (Windows NT 10.0; rv:74.0) Gecko/20100101 Firefox/74.0' --internal-urls '(.*?(contacts|calendar|accounts)\.google\.com.*?|.*?facebook\.com.*?)' --name Soundcloud --icon icon.png https://soundcloud.com
Running in verbose mode! This will produce a mountain of logs and is recommended only for troubleshooting or if you like Shakespeare.

Performing async options post-processing.
Got icon from options. Using it, no inferring needed
Got name Soundcloud from options. No inferring needed
Sanitized filename for Soundcloud : Soundcloud
options {
  packager: {
    appCopyright: undefined,
    appVersion: undefined,
    arch: 'x64',
    asar: false,
    buildVersion: undefined,
    darwinDarkModeSupport: true,
    dir: '/opt/brew/Cellar/nativefier/43.1.2/libexec/lib/node_modules/nativefier/app',
    electronVersion: '12.0.6',
    icon: 'icon.png',
    name: 'Soundcloud',
    out: '/private/var/folders/l1/f4rh7l7n0v59msb7psh91m7h0000gn/T/tmp.d0TS60q4',
    overwrite: false,
    platform: 'darwin',
    portable: false,
    targetUrl: 'https://soundcloud.com/',
    tmpdir: false,
    upgrade: false,
    upgradeFrom: undefined,
    win32metadata: {
      ProductName: 'Soundcloud',
      InternalName: 'Soundcloud',
      FileDescription: 'Soundcloud'
    }
  },
  nativefier: {
    accessibilityPrompt: true,
    alwaysOnTop: false,
    backgroundColor: null,
    basicAuthPassword: null,
    basicAuthUsername: null,
    blockExternalUrls: false,
    bookmarksMenu: null,
    bounce: true,
    browserwindowOptions: undefined,
    clearCache: false,
    counter: false,
    crashReporter: undefined,
    disableContextMenu: undefined,
    disableDevTools: undefined,
    disableGpu: false,
    diskCacheSize: null,
    disableOldBuildWarning: false,
    enableEs3Apis: false,
    fastQuit: false,
    fileDownloadOptions: undefined,
    flashPluginDir: null,
    fullScreen: false,
    globalShortcuts: null,
    hideWindowFrame: undefined,
    ignoreCertificate: false,
    ignoreGpuBlacklist: false,
    inject: [],
    insecure: false,
    internalUrls: '(.*?(contacts|calendar|accounts)\\.google\\.com.*?|.*?facebook\\.com.*?)',
    lang: undefined,
    maximize: false,
    nativefierVersion: '43.1.2',
    processEnvs: undefined,
    proxyRules: null,
    showMenuBar: false,
    singleInstance: true,
    titleBarStyle: null,
    tray: false,
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; rv:74.0) Gecko/20100101 Firefox/74.0',
    userAgentOverriden: true,
    verbose: true,
    versionString: undefined,
    width: 1280,
    height: 800,
    minWidth: undefined,
    minHeight: undefined,
    maxWidth: undefined,
    maxHeight: undefined,
    widevine: false,
    x: undefined,
    y: undefined,
    zoom: 1
  }
}

Preparing Electron app...
Copying electron app from /opt/brew/Cellar/nativefier/43.1.2/libexec/lib/node_modules/nativefier/app to /var/folders/l1/f4rh7l7n0v59msb7psh91m7h0000gn/T/nativefier-16-24-42-app--38040-lVH8sSyRrfpu
Writing app config to /var/folders/l1/f4rh7l7n0v59msb7psh91m7h0000gn/T/nativefier-16-24-42-app--38040-lVH8sSyRrfpu/nativefier.json
No files to inject, skipping copy.
Updating /var/folders/l1/f4rh7l7n0v59msb7psh91m7h0000gn/T/nativefier-16-24-42-app--38040-lVH8sSyRrfpu/package.json 'name' field to soundcloud-nativefier-914611

Converting icons...
Converting icon icon.png to /var/folders/l1/f4rh7l7n0v59msb7psh91m7h0000gn/T/nativefier-16-24-42-iconconv--38040-5hk13qE37T06/icon.icns. Calling shell command: "/opt/brew/Cellar/nativefier/43.1.2/libexec/lib/node_modules/nativefier/icon-scripts/convertToIcns" "icon.png" "/var/folders/l1/f4rh7l7n0v59msb7psh91m7h0000gn/T/nativefier-16-24-42-iconconv--38040-5hk13qE37T06/icon.icns"
Failed to convert icon to .icns, skipping. Error: Icon conversion failed with status code 1.
stdout:
stderr: identify: UnableToOpenConfigureFile `delegates.xml' @ warning/configure.c/GetConfigureOptions/702.
identify: NoDecodeDelegateForThisImageFormat `PNG' @ error/constitute.c/ReadImage/572.
convert: UnableToOpenConfigureFile `delegates.xml' @ warning/configure.c/GetConfigureOptions/702.
convert: NoDecodeDelegateForThisImageFormat `PNG' @ error/constitute.c/ReadImage/572.
convert: NoImagesDefined `convert_temp/icon.png' @ error/convert.c/ConvertImageCommand/3322.

    at iconShellHelper (/opt/brew/Cellar/nativefier/43.1.2/libexec/lib/node_modules/nativefier/src/helpers/iconShellHelpers.ts:46:11)
    at Object.convertToIcns (/opt/brew/Cellar/nativefier/43.1.2/libexec/lib/node_modules/nativefier/src/helpers/iconShellHelpers.ts:83:10)
    at Object.convertIconIfNecessary (/opt/brew/Cellar/nativefier/43.1.2/libexec/lib/node_modules/nativefier/src/build/buildIcon.ts:87:24)
    at Object.buildNativefierApp (/opt/brew/Cellar/nativefier/43.1.2/libexec/lib/node_modules/nativefier/src/build/buildNativefierApp.ts:173:3)
Copying icons if necessary
No icon specified in options; aborting

Packaging... This will take a few seconds, maybe minutes if the requested Electron isn't cached yet...
  electron-packager Electron Packager 15.2.0
  electron-packager Node v16.1.0
  electron-packager Host Operating system: darwin 20.5.0 (x64) +0ms
  electron-packager Packager Options: {"arch":"x64","asar":false,"darwinDarkModeSupport":true,"dir":"/var/folders/l1/f4rh7l7n0v59msb7psh91m7h0000gn/T/nativefier-16-24-42-app--38040-lVH8sSyRrfpu","electronVersion":"12.0.6","name":"Soundcloud","out":"/private/var/folders/l1/f4rh7l7n0v59msb7psh91m7h0000gn/T/tmp.d0TS60q4","overwrite":false,"platform":"darwin","portable":false,"targetUrl":"https://soundcloud.com/","tmpdir":false,"upgrade":false,"win32metadata":{"ProductName":"Soundcloud","InternalName":"Soundcloud","FileDescription":"Soundcloud"}} +1ms
  electron-packager Target Platforms: darwin +0ms
  electron-packager Target Architectures: x64 +0ms
  electron-packager Inferring appVersion from version in /var/folders/l1/f4rh7l7n0v59msb7psh91m7h0000gn/T/nativefier-16-24-42-app--38040-lVH8sSyRrfpu/package.json +0ms
  electron-packager Application name: Soundcloud +9ms
  electron-packager Target Electron version: 12.0.6 +0ms
  electron-packager Ignored path regular expressions: [
  '/package-lock\\.json$',
  '/yarn\\.lock$',
  '/\\.git($|/)',
  '/node_modules/\\.bin($|/)',
  '\\.o(bj)?$'
] +0ms
  electron-packager Downloading Electron with options {"platform":"darwin","arch":"x64","version":"12.0.6","artifactName":"electron"} +0ms
Packaging app for platform darwin x64 using electron v12.0.6
  electron-packager Creating /private/var/folders/l1/f4rh7l7n0v59msb7psh91m7h0000gn/T/tmp.d0TS60q4/darwin-x64-template +3ms
  electron-packager Extracting /Users/zriggle/Library/Caches/electron/739809e58a9d0011b22ab70d11516a49a099dadf81ec40aabf349af3c1154da6/electron-v12.0.6-darwin-x64.zip to /private/var/folders/l1/f4rh7l7n0v59msb7psh91m7h0000gn/T/tmp.d0TS60q4/darwin-x64-template +1ms
  electron-packager Initializing app in /private/var/folders/l1/f4rh7l7n0v59msb7psh91m7h0000gn/T/tmp.d0TS60q4/Soundcloud-darwin-x64 from /private/var/folders/l1/f4rh7l7n0v59msb7psh91m7h0000gn/T/tmp.d0TS60q4/darwin-x64-template template +0ms
  electron-packager Ignored paths based on the out param: [
  '/private/var/folders/l1/f4rh7l7n0v59msb7psh91m7h0000gn/T/tmp.d0TS60q4/Soundcloud-darwin-x64',
  '/private/var/folders/l1/f4rh7l7n0v59msb7psh91m7h0000gn/T/tmp.d0TS60q4/Soundcloud-darwin-arm64',
  '/private/var/folders/l1/f4rh7l7n0v59msb7psh91m7h0000gn/T/tmp.d0TS60q4/Soundcloud-linux-ia32',
  '/private/var/folders/l1/f4rh7l7n0v59msb7psh91m7h0000gn/T/tmp.d0TS60q4/Soundcloud-linux-x64',
  '/private/var/folders/l1/f4rh7l7n0v59msb7psh91m7h0000gn/T/tmp.d0TS60q4/Soundcloud-linux-armv7l',
  '/private/var/folders/l1/f4rh7l7n0v59msb7psh91m7h0000gn/T/tmp.d0TS60q4/Soundcloud-linux-arm64',
  '/private/var/folders/l1/f4rh7l7n0v59msb7psh91m7h0000gn/T/tmp.d0TS60q4/Soundcloud-linux-mips64el',
  '/private/var/folders/l1/f4rh7l7n0v59msb7psh91m7h0000gn/T/tmp.d0TS60q4/Soundcloud-mas-x64',
  '/private/var/folders/l1/f4rh7l7n0v59msb7psh91m7h0000gn/T/tmp.d0TS60q4/Soundcloud-mas-arm64',
  '/private/var/folders/l1/f4rh7l7n0v59msb7psh91m7h0000gn/T/tmp.d0TS60q4/Soundcloud-win32-ia32',
  '/private/var/folders/l1/f4rh7l7n0v59msb7psh91m7h0000gn/T/tmp.d0TS60q4/Soundcloud-win32-x64',
  '/private/var/folders/l1/f4rh7l7n0v59msb7psh91m7h0000gn/T/tmp.d0TS60q4/Soundcloud-win32-arm64'
] +2s
  electron-packager Renaming Electron to Soundcloud in /private/var/folders/l1/f4rh7l7n0v59msb7psh91m7h0000gn/T/tmp.d0TS60q4/Soundcloud-darwin-x64/Electron.app/Contents/MacOS +35ms
  electron-packager Renaming Electron Helper to Soundcloud Helper in /private/var/folders/l1/f4rh7l7n0v59msb7psh91m7h0000gn/T/tmp.d0TS60q4/Soundcloud-darwin-x64/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS +1ms
  electron-packager Renaming Electron Helper (Renderer) to Soundcloud Helper (Renderer) in /private/var/folders/l1/f4rh7l7n0v59msb7psh91m7h0000gn/T/tmp.d0TS60q4/Soundcloud-darwin-x64/Electron.app/Contents/Frameworks/Electron Helper (Renderer).app/Contents/MacOS +0ms
  electron-packager Renaming Electron Helper (Plugin) to Soundcloud Helper (Plugin) in /private/var/folders/l1/f4rh7l7n0v59msb7psh91m7h0000gn/T/tmp.d0TS60q4/Soundcloud-darwin-x64/Electron.app/Contents/Frameworks/Electron Helper (Plugin).app/Contents/MacOS +1ms
  electron-packager Renaming Electron Helper (GPU) to Soundcloud Helper (GPU) in /private/var/folders/l1/f4rh7l7n0v59msb7psh91m7h0000gn/T/tmp.d0TS60q4/Soundcloud-darwin-x64/Electron.app/Contents/Frameworks/Electron Helper (GPU).app/Contents/MacOS +0ms
  electron-packager Renaming Electron Helper.app to Soundcloud Helper.app in /private/var/folders/l1/f4rh7l7n0v59msb7psh91m7h0000gn/T/tmp.d0TS60q4/Soundcloud-darwin-x64/Electron.app/Contents/Frameworks +0ms
  electron-packager Renaming Electron Helper (Renderer).app to Soundcloud Helper (Renderer).app in /private/var/folders/l1/f4rh7l7n0v59msb7psh91m7h0000gn/T/tmp.d0TS60q4/Soundcloud-darwin-x64/Electron.app/Contents/Frameworks +0ms
  electron-packager Renaming Electron Helper (Plugin).app to Soundcloud Helper (Plugin).app in /private/var/folders/l1/f4rh7l7n0v59msb7psh91m7h0000gn/T/tmp.d0TS60q4/Soundcloud-darwin-x64/Electron.app/Contents/Frameworks +0ms
  electron-packager Renaming Electron Helper (GPU).app to Soundcloud Helper (GPU).app in /private/var/folders/l1/f4rh7l7n0v59msb7psh91m7h0000gn/T/tmp.d0TS60q4/Soundcloud-darwin-x64/Electron.app/Contents/Frameworks +0ms

Finalizing build...
App built to /private/var/folders/l1/f4rh7l7n0v59msb7psh91m7h0000gn/T/tmp.d0TS60q4/Soundcloud-darwin-x64, move to wherever it makes sense for you and run the app bundle.
```
</details>

**Expected behavior**

Nativefier app should have an icon.  I built this using the same script I've always used, and it is failing on the current nativefier.

**Actual behavior**

An error message is thrown, and none of my Nativefier apps have an icon.

```
Converting icons...
Converting icon icon.png to /var/folders/l1/f4rh7l7n0v59msb7psh91m7h0000gn/T/nativefier-16-24-42-iconconv--38040-5hk13qE37T06/icon.icns. Calling shell command: "/opt/brew/Cellar/nativefier/43.1.2/libexec/lib/node_modules/nativefier/icon-scripts/convertToIcns" "icon.png" "/var/folders/l1/f4rh7l7n0v59msb7psh91m7h0000gn/T/nativefier-16-24-42-iconconv--38040-5hk13qE37T06/icon.icns"
Failed to convert icon to .icns, skipping. Error: Icon conversion failed with status code 1.
stdout:
stderr: identify: UnableToOpenConfigureFile `delegates.xml' @ warning/configure.c/GetConfigureOptions/702.
identify: NoDecodeDelegateForThisImageFormat `PNG' @ error/constitute.c/ReadImage/572.
convert: UnableToOpenConfigureFile `delegates.xml' @ warning/configure.c/GetConfigureOptions/702.
convert: NoDecodeDelegateForThisImageFormat `PNG' @ error/constitute.c/ReadImage/572.
convert: NoImagesDefined `convert_temp/icon.png' @ error/convert.c/ConvertImageCommand/3322.
```

**Debug info**

- Console logs of your `nativefier` build command, with `--verbose` flag. 
  - See above
- If the bug happens at app run time, the in-app DevTools console logs (open it with F12)
  - At build time
- Error messages
  - See above
- Screenshots
  - Not applicable
- Anything else relevant!

**Context**

```
$ nativefier --version
43.1.2

$ node --version
v16.1.0

$ npm --version
7.11.2

$ sw_vers
ProductName:	macOS
ProductVersion:	11.4
BuildVersion:	20F5055c
```

**Comment by cmangla** [comment]
A search for `identify: UnableToOpenConfigureFile delegates.xml` reveals reports of this issue arising due to errors in packaging of ImageMagick. See

https://legacy.imagemagick.org/discourse-server/viewtopic.php?t=15350

Perhaps you could check if ImageMagick is working on your system at all, using `identify something.png`. Nativefier also supports GraphicsMagick now, but if ImageMagick is installed it will go with that before looking for the alternative.

**Comment by zachriggle** [comment]
Back on the machine that originally reproduced the issue, I do see an issue with and `identify icon.png`.

Note that here, Homebrew is also installed at a non-standard location, `/opt/brew`, which is not of my choosing but enforced by company policy so as not to pollute / take precedence over company-installed files in `/usr/local` or to precede binaries installed in e.g. `/bin` or `/usr/bin` (i.e., `/opt/brew/bin` comes LAST in `$PATH`).

How can I get `nativefier` to use GraphicsMagick instead, as a work-around?

```
$ brew info imagemagick
imagemagick: stable 7.0.11-11 (bottled), HEAD
Tools and libraries to manipulate images in many formats
https://www.imagemagick.org/
/opt/brew/Cellar/imagemagick/7.0.11-11 (798 files, 30.2MB) *
  Poured from bottle on 2021-05-06 at 03:09:57
/opt/brew/Cellar/imagemagick/7.0.11-11.reinstall (798 files, 30.2MB)
  Poured from bottle on 2021-05-06 at 03:05:43
From: https://github.pie.apple.com/homebrew/homebrew-core/blob/HEAD/Formula/imagemagick.rb
License: ImageMagick
==> Dependencies
Build: pkg-config ✔
Required: freetype ✔, jpeg ✔, libheif ✔, liblqr ✔, libomp ✔, libpng ✔, libtiff ✔, libtool ✔, little-cms2 ✔, openexr ✔, openjpeg ✔, webp ✔, xz ✔
==> Options
--HEAD
	Install HEAD version

$ which identify
/opt/brew/bin/identify

$ identify --version
Version: ImageMagick 7.0.11-11 Q16 x86_64 2021-05-04 https://imagemagick.org
Copyright: (C) 1999-2021 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenMP(4.5)
Delegates (built-in): bzlib freetype gslib heic jng jp2 jpeg lcms lqr ltdl lzma openexr png ps tiff webp xml zlib

$ curl -s https://images.vexels.com/media/users/3/137412/isolated/preview/1802b9d8ce3c819eebe90a86bbb61077-soundcloud-icon-logo-by-vexels.png > icon.png

$ identify icon.png
identify: UnableToOpenConfigureFile `delegates.xml' @ warning/configure.c/GetConfigureOptions/702.
identify: NoDecodeDelegateForThisImageFormat `PNG' @ error/constitute.c/ReadImage/572.
```

**Comment by cmangla** [comment]
The scripts essentially first look for ImageMagick commands (`convert`, `identify`, etc.)  in your `$PATH`, and then look for GraphicsMagick `gm` command. So if you, for example, uninstall ImageMagick and install GraphicsMagick, that might convince the scripts to use the latter.

**Comment by cmangla** [comment]
> After everything succeeded with GraphicsMagick, I reinstalled `brew install imagemagick` and ran the script again, and ran into the issues I originally started this thread for. Is there any way to specify to `nativefier` to prefer one over the other?

Unfortunately there isn't. The preference order is hard-coded in the scripts. It would be a useful if the preference order was configurable.

**Comment by cmangla** [comment]
@zachriggle Many thanks for testing that with GraphicsMagick .

**Comment by cmangla** [comment]
Good idea @TheCleric . The following lines are what the scripts do, which you could try to fool using aliases:

```bash
type gm &>/dev/null && gm version | grep GraphicsMagick &>/dev/null && HAVE_GRAPHICSMAGICK=true && CONVERT="gm convert"
type convert &>/dev/null && HAVE_IMAGEMAGICK=true && CONVERT="convert"
type sips &>/dev/null && HAVE_SIPS=true
```

**Comment by TheCleric** [comment]
@zachriggle have you been able to try my proposed workaround?

**Comment by zachriggle** [comment]
The workaround did work.

Also, the root-cause of the issue is that Homebrew's imagemagick hard-codes paths to `/usr/local/Cellar/xxx` where I have Homebrew installed at a different location (per my company's setup instructions).

Creating a symlink at `/usr/local/Cellar` to point to my actual `Cellar` resolves the issue.
