### ISSUE TITLE
nativefier --upgrade saves upgraded app in current working directory instead of directory where app currently is located

### ISSUE THREAD

**Issue by mattruzzi** [nativefier/nativefier#1216]
**Homework**

- [x] I looked at `nativefier --help` and https://github.com/nativefier/nativefier/blob/master/API.md
- [x] I checked the [Troubleshooting section of the README](https://github.com/nativefier/nativefier/blob/master/README.md#troubleshooting).
- [ ] I searched existing issues, open & closed. Yes, my bug is new.
- [x] I'm using the latest version available at https://github.com/nativefier/nativefier/releases

**Bug description**

`nativefier --upgrade` saves upgraded app in current working directory instead of directory where app currently is located. 

**Steps to reproduce**

```
❯ nativefier --upgrade ~/Applications/Example\ Domain-darwin-x64/Example\ Domain.app --verbose
Running in verbose mode! This will produce a mountain of logs and is recommended only for troubleshooting or if you like Shakespeare.

Performing async options post-processing.
mozilla/5.0 (macintosh; intel mac os x 10_12_5) applewebkit/537.36 (khtml, like gecko) chrome/89.0.4389.82 safari/537.36 not found in [ 'edge', 'firefox', 'safari' ]
Got icon from options. Using it, no inferring needed
Got name Example Domain from options. No inferring needed
Sanitized filename for Example Domain : Example Domain
options {
  packager: {
    appCopyright: undefined,
    appVersion: undefined,
    arch: 'x64',
    asar: false,
    buildVersion: undefined,
    darwinDarkModeSupport: true,
    dir: '/Users/USER/.n/lib/node_modules/nativefier/app',
    electronVersion: '12.0.10',
    icon: '/Users/USER/Applications/Example Domain-darwin-x64/Example Domain.app/Contents/Resources/electron.icns',
    name: 'Example Domain',
    out: '/Users/USER',
    overwrite: true,
    platform: 'darwin',
    portable: false,
    targetUrl: 'https://example.com/',
    tmpdir: false,
    upgrade: true,
    upgradeFrom: '/Users/USER/Applications/Example Domain-darwin-x64/Example Domain.app',
    win32metadata: { ProductName: '', InternalName: '', FileDescription: '' }
  },
  nativefier: {
    accessibilityPrompt: true,
    alwaysOnTop: false,
    backgroundColor: null,
    basicAuthPassword: null,
    basicAuthUsername: null,
    blockExternalUrls: false,
    bookmarksMenu: null,
    bounce: false,
    browserwindowOptions: {},
    clearCache: false,
    counter: false,
    crashReporter: undefined,
    disableContextMenu: false,
    disableDevTools: false,
    disableGpu: false,
    diskCacheSize: null,
    disableOldBuildWarning: false,
    enableEs3Apis: false,
    fastQuit: false,
    fileDownloadOptions: {},
    flashPluginDir: null,
    fullScreen: false,
    globalShortcuts: null,
    hideWindowFrame: false,
    ignoreCertificate: false,
    ignoreGpuBlacklist: false,
    inject: [],
    insecure: false,
    internalUrls: null,
    lang: undefined,
    maximize: false,
    nativefierVersion: '44.0.0',
    processEnvs: {},
    proxyRules: null,
    showMenuBar: false,
    singleInstance: false,
    titleBarStyle: null,
    tray: false,
    userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Safari/537.36',
    userAgentHonest: false,
    verbose: true,
    versionString: undefined,
    width: 1280,
    height: 800,
    minWidth: undefined,
    minHeight: undefined,
    maxWidth: undefined,
    maxHeight: undefined,
    widevine: false,
    x: undefined,
    y: undefined,
    zoom: 1
  }
}

Preparing Electron app...
Copying electron app from /Users/USER/.n/lib/node_modules/nativefier/app to /var/folders/x4/d6xhrn615_15s2bdvqp7rtw80000gr/T/nativefier-16-52-34-app--38131-223qXQkZDU4B
Writing app config to /var/folders/x4/d6xhrn615_15s2bdvqp7rtw80000gr/T/nativefier-16-52-34-app--38131-223qXQkZDU4B/nativefier.json
No files to inject, skipping copy.
Updating /var/folders/x4/d6xhrn615_15s2bdvqp7rtw80000gr/T/nativefier-16-52-34-app--38131-223qXQkZDU4B/package.json 'name' field to example-domain-nativefier-182cce

Converting icons...
Building for macOS and icon is already a .icns, no conversion needed
Copying icons if necessary
No copying necessary on macOS; aborting

Packaging... This will take a few seconds, maybe minutes if the requested Electron isn't cached yet...
  electron-packager Electron Packager 15.2.0
  electron-packager Node v16.3.0
  electron-packager Host Operating system: darwin 17.7.0 (x64) +0ms
  electron-packager Packager Options: {"arch":"x64","asar":false,"darwinDarkModeSupport":true,"dir":"/var/folders/x4/d6xhrn615_15s2bdvqp7rtw80000gr/T/nativefier-16-52-34-app--38131-223qXQkZDU4B","electronVersion":"12.0.10","icon":"/Users/USER/Applications/Example Domain-darwin-x64/Example Domain.app/Contents/Resources/electron.icns","name":"Example Domain","out":"/Users/USER","overwrite":true,"platform":"darwin","portable":false,"targetUrl":"https://example.com/","tmpdir":false,"upgrade":true,"upgradeFrom":"/Users/USER/Applications/Example Domain-darwin-x64/Example Domain.app","win32metadata":{"ProductName":"","InternalName":"","FileDescription":""}} +1ms
  electron-packager Target Platforms: darwin +0ms
  electron-packager Target Architectures: x64 +0ms
  electron-packager Inferring appVersion from version in /var/folders/x4/d6xhrn615_15s2bdvqp7rtw80000gr/T/nativefier-16-52-34-app--38131-223qXQkZDU4B/package.json +0ms
  electron-packager Application name: Example Domain +15ms
  electron-packager Target Electron version: 12.0.10 +0ms
  electron-packager Ignored path regular expressions: [
  '/package-lock\\.json$',
  '/yarn\\.lock$',
  '/\\.git($|/)',
  '/node_modules/\\.bin($|/)',
  '\\.o(bj)?$'
] +0ms
  electron-packager Downloading Electron with options {"platform":"darwin","arch":"x64","version":"12.0.10","artifactName":"electron"} +0ms
Packaging app for platform darwin x64 using electron v12.0.10
  electron-packager Creating /Users/USER/darwin-x64-template +5ms
  electron-packager Extracting /Users/USER/Library/Caches/electron/fe82eb0272a083ac9c8100be1631e54e7199d39ec5441c611bd374f326bddbaa/electron-v12.0.10-darwin-x64.zip to /Users/USER/darwin-x64-template +1ms
  electron-packager Initializing app in /Users/USER/Example Domain-darwin-x64 from /Users/USER/darwin-x64-template template +0ms
  electron-packager Ignored paths based on the out param: [
  '/Users/USER/Example Domain-darwin-x64',
  '/Users/USER/Example Domain-darwin-arm64',
  '/Users/USER/Example Domain-linux-ia32',
  '/Users/USER/Example Domain-linux-x64',
  '/Users/USER/Example Domain-linux-armv7l',
  '/Users/USER/Example Domain-linux-arm64',
  '/Users/USER/Example Domain-linux-mips64el',
  '/Users/USER/Example Domain-mas-x64',
  '/Users/USER/Example Domain-mas-arm64',
  '/Users/USER/Example Domain-win32-ia32',
  '/Users/USER/Example Domain-win32-x64',
  '/Users/USER/Example Domain-win32-arm64'
] +4s
  electron-packager Copying icon "/Users/USER/Applications/Example Domain-darwin-x64/Example Domain.app/Contents/Resources/electron.icns" to app's Resources as "electron.icns" +0ms
  electron-packager Renaming Electron to Example Domain in /Users/USER/Example Domain-darwin-x64/Electron.app/Contents/MacOS +92ms
  electron-packager Renaming Electron Helper to Example Domain Helper in /Users/USER/Example Domain-darwin-x64/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS +1ms
  electron-packager Renaming Electron Helper (Renderer) to Example Domain Helper (Renderer) in /Users/USER/Example Domain-darwin-x64/Electron.app/Contents/Frameworks/Electron Helper (Renderer).app/Contents/MacOS +1ms
  electron-packager Renaming Electron Helper (Plugin) to Example Domain Helper (Plugin) in /Users/USER/Example Domain-darwin-x64/Electron.app/Contents/Frameworks/Electron Helper (Plugin).app/Contents/MacOS +0ms
  electron-packager Renaming Electron Helper (GPU) to Example Domain Helper (GPU) in /Users/USER/Example Domain-darwin-x64/Electron.app/Contents/Frameworks/Electron Helper (GPU).app/Contents/MacOS +0ms
  electron-packager Renaming Electron Helper.app to Example Domain Helper.app in /Users/USER/Example Domain-darwin-x64/Electron.app/Contents/Frameworks +0ms
  electron-packager Renaming Electron Helper (Renderer).app to Example Domain Helper (Renderer).app in /Users/USER/Example Domain-darwin-x64/Electron.app/Contents/Frameworks +0ms
  electron-packager Renaming Electron Helper (Plugin).app to Example Domain Helper (Plugin).app in /Users/USER/Example Domain-darwin-x64/Electron.app/Contents/Frameworks +1ms
  electron-packager Renaming Electron Helper (GPU).app to Example Domain Helper (GPU).app in /Users/USER/Example Domain-darwin-x64/Electron.app/Contents/Frameworks +0ms

Finalizing build...
App built to /Users/USER/Example Domain-darwin-x64, move to wherever it makes sense for you and run the app bundle.
```

**Expected behavior**

Saves updated app to ~/Applications

**Actual behavior**
Saves updated app to home folder ~/
(current working directory)

**Debug info**

- Console logs of your `nativefier` build command, with `--verbose` flag
- If the bug happens at app run time, the in-app DevTools console logs (open it with F12)
- Error messages
- Screenshots
- Anything else relevant!

**Context**
Where I discovered this: 
https://github.com/mattruzzi/nativefier-gui/tree/feat--Upgrade-existing-apps
I was trying to add a menu to nativefier-gui update existing nativefier apps and was running the nativfier programmatic API and got the following:
```
Preparing Electron app...

Converting icons...

Packaging... This will take a few seconds, maybe minutes if the requested Electron isn't cached yet...
Packaging app for platform darwin x64 using electron v12.0.10
Error: Invalid package /Users/USER/Documents/github2/nativefier-gui-2/darwin-x64-template/Electron.app/Contents/Resources/default_app.asar
    at createError (electron/js2c/asar_bundle.js:5:1585)
    at Object.t.<computed> [as open] (electron/js2c/asar_bundle.js:5:2419)
    at _openWriteFs (internal/fs/streams.js:370:15)
    at new WriteStream (internal/fs/streams.js:343:5)
    at createWriteStream (fs.js:2008:10)
    at Extractor.extractEntry (/Users/USER/Documents/github2/nativefier-gui-2/node_modules/electron-packager/node_modules/extract-zip/index.js:132:34)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at ZipFile.<anonymous> (/Users/USER/Documents/github2/nativefier-gui-2/node_modules/electron-packager/node_modules/extract-zip/index.js:65:11)
```
```node
function updateApp(path) {
    const appPath = dialog.showOpenDialogSync(null, {
        properties: ["openFile", "openDirectory"],
        buttonLabel: "Update Nativefier App",
    })[0];
    console.log("Upgrading " + appPath);
    const args = { "upgrade": appPath }
    nativefier(args, function (error, appPath) {
        if (error) {
            console.error(error);
            return;
        }
        console.log("App has been nativefied to", appPath);
    });
}
```

 - Nativefier: 44.0.0
 - Node.js: v16.3.0
 - Npm: 7.16.0
 - OS: Mac OS X 10.13.6
 - Is it a regression? If yes, what's the last working / first broken version?
 - Additional context: (for example: "I'm behind a proxy, with configuration X and protocol Y")

**Comment by TheCleric** [comment]
I noticed this yesterday as well. Looking into a fix but am currently at the "how did this ever work?" stage of debugging.

**Comment by mattruzzi** [comment]
@TheCleric @ronjouch This still is an issue on `nativefier@44.0.6`. 
```sh
cd /tmp
git clone https://github.com/mattruzzi/nativefier-gui.git --branch feat--Upgrade-existing-apps
cd nativefier-gui
npm install
npm start
```
Then choose `File > Update Existing App` and select a nativefier app. It will create a folder called darwin-x64-template (or whatever your platform is) in /tmp/nativefier-gui. 

```sh
❯ ls
README.md           node_modules        package.json        src
darwin-x64-template package-lock.json   screenshot.png
```

**Comment by mattruzzi** [comment]
Now I am seeing a slightly different issue where it keeps the old app and places the upgraded version inside a folder in the same folder as the old app:
```zsh
❯ nativefier --upgrade /Users/USER/Applications/Duolingo-darwin-x64/Duolingo.app

Preparing Electron app...

Converting icons...

Packaging... This will take a few seconds, maybe minutes if the requested Electron isn't cached yet...
Packaging app for platform darwin x64 using electron v13.1.7

Finalizing build...
App built to /Users/USER/Applications/Duolingo-darwin-x64/Duolingo-darwin-x64, move to wherever it makes sense for you and run the app bundle.

~ 33s
❯
```
![](https://user-images.githubusercontent.com/68619790/126206352-2c2f33ad-21a5-4c30-82db-b6bd718a3a33.png)

**Comment by TheCleric** [comment]
> Now I am seeing a slightly different issue where it keeps the old app and places the upgraded version inside a folder in the same folder as the old app:

Weird. I don't think I've even touched any of this yet...
