### ISSUE TITLE
[regression/linux] Tray icon (backed by gnome-shell-extension-appindicator) consumes all trayicon area horizontal space

### ISSUE THREAD

**Issue by ronjouch** [nativefier/nativefier#1237]
**Bug description**

Our tray icon on Linux is horribly broken and consumes all available horizontal space.

It for sure hasn't always been the case (I've tested it on Linux when it was introduced).

I dunno yet if it's a regression in...

- gnome-shell-extension-appindicator...
- ... or ours, and when it was introduced if it's ours.

**Steps to reproduce**

<details>
  <summary>CLI and app logs for <code>nativefier --verbose --tray true https://npmjs.com</code></summary>

```

08:29:07 /o/nativefier (master|✔) ntest --verbose --tray true 'https://npmjs.com'
Running in verbose mode! This will produce a mountain of logs and is recommended only for troubleshooting or if you like Shakespeare.
Inferred platform linux

Performing async options post-processing.
Inferring icon for https://npmjs.com/ on linux
Inferring icon from store for https://npmjs.com/ on linux
Allowed icon formats when building for linux: [ '.png', '.ico' ]
Sanitized filename for ntest : ntest
Got 249 icons from gitcloud
Max icon match score: 0
No relevant icon in store.
Trying to extract a .png icon from the page.
Got an icon from the page.
Writing 1.7 kb icon to /tmp/nativefier-8-29-8-iconinfer--209708-kOYREELzq0wD/icon.png
options {
  packager: {
    appCopyright: undefined,
    appVersion: undefined,
    arch: 'x64',
    asar: false,
    buildVersion: undefined,
    darwinDarkModeSupport: false,
    dir: '/opt/nativefier/app',
    electronVersion: '12.0.11',
    icon: '/tmp/nativefier-8-29-8-iconinfer--209708-kOYREELzq0wD/icon.png',
    name: 'ntest',
    out: '/tmp/ntest/',
    overwrite: true,
    platform: 'linux',
    portable: false,
    targetUrl: 'https://npmjs.com/',
    tmpdir: false,
    upgrade: false,
    upgradeFrom: undefined,
    win32metadata: {
      ProductName: 'ntest',
      InternalName: 'ntest',
      FileDescription: 'ntest'
    }
  },
  nativefier: {
    accessibilityPrompt: true,
    alwaysOnTop: false,
    backgroundColor: undefined,
    basicAuthPassword: undefined,
    basicAuthUsername: undefined,
    blockExternalUrls: false,
    bookmarksMenu: undefined,
    bounce: false,
    browserwindowOptions: undefined,
    clearCache: false,
    counter: false,
    crashReporter: undefined,
    disableContextMenu: false,
    disableDevTools: false,
    disableGpu: false,
    diskCacheSize: undefined,
    disableOldBuildWarning: false,
    enableEs3Apis: false,
    fastQuit: false,
    fileDownloadOptions: undefined,
    flashPluginDir: undefined,
    fullScreen: false,
    globalShortcuts: undefined,
    hideWindowFrame: false,
    ignoreCertificate: false,
    ignoreGpuBlacklist: false,
    inject: [],
    insecure: false,
    internalUrls: undefined,
    lang: undefined,
    maximize: false,
    nativefierVersion: '44.0.4',
    processEnvs: undefined,
    proxyRules: undefined,
    showMenuBar: false,
    singleInstance: false,
    titleBarStyle: undefined,
    tray: true,
    userAgent: undefined,
    userAgentHonest: false,
    verbose: true,
    versionString: undefined,
    width: 1280,
    height: 800,
    minWidth: undefined,
    minHeight: undefined,
    maxWidth: undefined,
    maxHeight: undefined,
    widevine: false,
    x: undefined,
    y: undefined,
    zoom: 1
  }
}

Preparing Electron app...
Copying electron app from /opt/nativefier/app to /tmp/nativefier-8-29-8-app--209708-LMdxlWKkA4av
Writing app config to /tmp/nativefier-8-29-8-app--209708-LMdxlWKkA4av/nativefier.json
No files to inject, skipping copy.
Updating /tmp/nativefier-8-29-8-app--209708-LMdxlWKkA4av/package.json 'name' field to ntest-nativefier-411f25

Converting icons...
Building for Linux and icon is already a .png, no conversion needed
Copying icons if necessary
Copying icon /tmp/nativefier-8-29-8-iconinfer--209708-kOYREELzq0wD/icon.png to /tmp/nativefier-8-29-8-app--209708-LMdxlWKkA4av/icon.png

Packaging... This will take a few seconds, maybe minutes if the requested Electron isn't cached yet...
  electron-packager Electron Packager 15.2.0
  electron-packager Node v16.3.0
  electron-packager Host Operating system: linux 5.12.12-zen1-1-zen (x64) +0ms
  electron-packager Packager Options: {"arch":"x64","asar":false,"darwinDarkModeSupport":false,"dir":"/tmp/nativefier-8-29-8-app--209708-LMdxlWKkA4av","electronVersion":"12.0.11","icon":"/tmp/nativefier-8-29-8-iconinfer--209708-kOYREELzq0wD/icon.png","name":"ntest","out":"/tmp/ntest/","overwrite":true,"platform":"linux","portable":false,"targetUrl":"https://npmjs.com/","tmpdir":false,"upgrade":false,"win32metadata":{"ProductName":"ntest","InternalName":"ntest","FileDescription":"ntest"}} +1ms
  electron-packager Target Platforms: linux +0ms
  electron-packager Target Architectures: x64 +0ms
  electron-packager Inferring appVersion from version in /tmp/nativefier-8-29-8-app--209708-LMdxlWKkA4av/package.json +0ms
  electron-packager Application name: ntest +5ms
  electron-packager Target Electron version: 12.0.11 +0ms
  electron-packager Ignored path regular expressions: [
  '/package-lock\\.json$',
  '/yarn\\.lock$',
  '/\\.git($|/)',
  '/node_modules/\\.bin($|/)',
  '\\.o(bj)?$',
  '/tmp/electron-packager'
] +0ms
  electron-packager Downloading Electron with options {"platform":"linux","arch":"x64","version":"12.0.11","artifactName":"electron"} +0ms
Packaging app for platform linux x64 using electron v12.0.11
  electron-packager Creating /tmp/ntest/linux-x64-template +5ms
  electron-packager Extracting /home/ronj/.cache/electron/e0e0fe687c746f830a615f37fe4a2f2e9629a4ed38a6ab119cb562152366c859/electron-v12.0.11-linux-x64.zip to /tmp/ntest/linux-x64-template +0ms
  electron-packager Initializing app in /tmp/ntest/ntest-linux-x64 from /tmp/ntest/linux-x64-template template +0ms
  electron-packager Ignored paths based on the out param: [ '/tmp/ntest' ] +2s
  electron-packager Renaming electron to ntest in /tmp/ntest/ntest-linux-x64 +128ms

Finalizing build...
App built to /tmp/ntest/ntest-linux-x64, move to wherever it makes sense for you and run the contained executable file (prefixing with ./ if necessary)
Menu/desktop shortcuts are up to you, because Nativefier cannot know where you're going to move the app. Search for "linux .desktop file" for help, or see https://wiki.archlinux.org/index.php/Desktop_entries
DONE BUILDING! Running...

appArgs {
  accessibilityPrompt: true,
  alwaysOnTop: false,
  arch: 'x64',
  asar: false,
  blockExternalUrls: false,
  bounce: false,
  buildDate: 1624364950902,
  clearCache: false,
  counter: false,
  darwinDarkModeSupport: false,
  disableContextMenu: false,
  disableDevTools: false,
  disableGpu: false,
  disableOldBuildWarning: false,
  electronVersionUsed: '12.0.11',
  enableEs3Apis: false,
  fastQuit: false,
  fullScreen: false,
  height: 800,
  hideWindowFrame: false,
  ignoreCertificate: false,
  ignoreGpuBlacklist: false,
  insecure: false,
  isUpgrade: false,
  maximize: false,
  name: 'ntest',
  nativefierVersion: '44.0.4',
  portable: false,
  showMenuBar: false,
  singleInstance: false,
  targetUrl: 'https://npmjs.com/',
  tray: true,
  userAgentHonest: false,
  width: 1280,
  widevine: false,
  win32metadata: {
    ProductName: 'ntest',
    InternalName: 'ntest',
    FileDescription: 'ntest'
  },
  zoom: 1,
  oldBuildWarningText: ''
}
Not loading override URL passed as argument, because failed to parse: --verbose TypeError [ERR_INVALID_URL]: Invalid URL: --verbose
    at onParseError (internal/url.js:259:9)
    at new URL (internal/url.js:335:5)
    at Object.<anonymous> (/tmp/ntest/ntest-linux-x64/resources/app/lib/webpack:/nativefier-placeholder/src/main.ts:67:5)
    at __webpack_require__ (/tmp/ntest/ntest-linux-x64/resources/app/lib/webpack:/nativefier-placeholder/webpack/bootstrap:19:1)
    at /tmp/ntest/ntest-linux-x64/resources/app/lib/webpack:/nativefier-placeholder/webpack/startup:4:1
    at Object.<anonymous> (/tmp/ntest/ntest-linux-x64/resources/app/lib/main.js:10993:12)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14) {
  input: '--verbose',
  code: 'ERR_INVALID_URL'
}
ready
getDefaultWindowOptions {
  options: {
    accessibilityPrompt: true,
    alwaysOnTop: false,
    arch: 'x64',
    asar: false,
    blockExternalUrls: false,
    bounce: false,
    buildDate: 1624364950902,
    clearCache: false,
    counter: false,
    darwinDarkModeSupport: false,
    disableContextMenu: false,
    disableDevTools: false,
    disableGpu: false,
    disableOldBuildWarning: false,
    electronVersionUsed: '12.0.11',
    enableEs3Apis: false,
    fastQuit: false,
    fullScreen: false,
    height: 800,
    hideWindowFrame: false,
    ignoreCertificate: false,
    ignoreGpuBlacklist: false,
    insecure: false,
    isUpgrade: false,
    maximize: false,
    name: 'ntest',
    nativefierVersion: '44.0.4',
    portable: false,
    showMenuBar: false,
    singleInstance: false,
    targetUrl: 'https://npmjs.com/',
    tray: true,
    userAgentHonest: false,
    width: 1280,
    widevine: false,
    win32metadata: {
      ProductName: 'ntest',
      InternalName: 'ntest',
      FileDescription: 'ntest'
    },
    zoom: 1,
    oldBuildWarningText: ''
  },
  webPreferences: {},
  defaultOptions: {
    fullscreenable: true,
    tabbingIdentifier: undefined,
    title: 'ntest',
    webPreferences: {
      javascript: true,
      nodeIntegration: false,
      preload: '/tmp/ntest/ntest-linux-x64/resources/app/lib/preload.js',
      plugins: true,
      webSecurity: true,
      zoomFactor: 1
    }
  }
}
app.browser-window-created {
  event: {
    preventDefault: [Function: preventDefault],
    sendReply: [Function: sendReply]
  },
  window: BrowserWindow {
    setBounds: [Function (anonymous)],
    _events: [Object: null prototype] {
      blur: [Function (anonymous)],
      focus: [Function (anonymous)],
      show: [Function: visibilityChanged],
      hide: [Function: visibilityChanged],
      minimize: [Function: visibilityChanged],
      maximize: [Function: visibilityChanged],
      restore: [Function: visibilityChanged]
    },
    _eventsCount: 7
  }
}
createMenu {
  options: {
    accessibilityPrompt: true,
    alwaysOnTop: false,
    arch: 'x64',
    asar: false,
    blockExternalUrls: false,
    bounce: false,
    buildDate: 1624364950902,
    clearCache: false,
    counter: false,
    darwinDarkModeSupport: false,
    disableContextMenu: false,
    disableDevTools: false,
    disableGpu: false,
    disableOldBuildWarning: false,
    electronVersionUsed: '12.0.11',
    enableEs3Apis: false,
    fastQuit: false,
    fullScreen: false,
    height: 800,
    hideWindowFrame: false,
    ignoreCertificate: false,
    ignoreGpuBlacklist: false,
    insecure: false,
    isUpgrade: false,
    maximize: false,
    name: 'ntest',
    nativefierVersion: '44.0.4',
    portable: false,
    showMenuBar: false,
    singleInstance: false,
    targetUrl: 'https://npmjs.com/',
    tray: true,
    userAgentHonest: false,
    width: 1280,
    widevine: false,
    win32metadata: {
      ProductName: 'ntest',
      InternalName: 'ntest',
      FileDescription: 'ntest'
    },
    zoom: 1,
    oldBuildWarningText: ''
  },
  mainWindow: BrowserWindow {
    setBounds: [Function (anonymous)],
    _events: [Object: null prototype] {
      blur: [Function (anonymous)],
      focus: [Function (anonymous)],
      show: [Function: visibilityChanged],
      hide: [Function: visibilityChanged],
      minimize: [Function: visibilityChanged],
      maximize: [Function: visibilityChanged],
      restore: [Function: visibilityChanged],
      'new-tab': [Function (anonymous)],
      resize: [Function: stateChangeHandler],
      move: [Function: stateChangeHandler],
      close: [Function: closeHandler],
      closed: [Function: closedHandler]
    },
    _eventsCount: 12,
    devToolsWebContents: [Getter]
  }
}
initContextMenu {
  options: {
    accessibilityPrompt: true,
    alwaysOnTop: false,
    arch: 'x64',
    asar: false,
    blockExternalUrls: false,
    bounce: false,
    buildDate: 1624364950902,
    clearCache: false,
    counter: false,
    darwinDarkModeSupport: false,
    disableContextMenu: false,
    disableDevTools: false,
    disableGpu: false,
    disableOldBuildWarning: false,
    electronVersionUsed: '12.0.11',
    enableEs3Apis: false,
    fastQuit: false,
    fullScreen: false,
    height: 800,
    hideWindowFrame: false,
    ignoreCertificate: false,
    ignoreGpuBlacklist: false,
    insecure: false,
    isUpgrade: false,
    maximize: false,
    name: 'ntest',
    nativefierVersion: '44.0.4',
    portable: false,
    showMenuBar: false,
    singleInstance: false,
    targetUrl: 'https://npmjs.com/',
    tray: true,
    userAgentHonest: false,
    width: 1280,
    widevine: false,
    win32metadata: {
      ProductName: 'ntest',
      InternalName: 'ntest',
      FileDescription: 'ntest'
    },
    zoom: 1,
    oldBuildWarningText: ''
  },
  window: BrowserWindow {
    setBounds: [Function (anonymous)],
    _events: [Object: null prototype] {
      blur: [Function (anonymous)],
      focus: [Function (anonymous)],
      show: [Function: visibilityChanged],
      hide: [Function: visibilityChanged],
      minimize: [Function: visibilityChanged],
      maximize: [Function: visibilityChanged],
      restore: [Function: visibilityChanged],
      'new-tab': [Function (anonymous)],
      resize: [Function: stateChangeHandler],
      move: [Function: stateChangeHandler],
      close: [Function: closeHandler],
      closed: [Function: closedHandler]
    },
    _eventsCount: 12,
    devToolsWebContents: [Getter]
  }
}
app.browser-window-focus {
  event: {
    preventDefault: [Function: preventDefault],
    sender: BrowserWindow {
      setBounds: [Function (anonymous)],
      _events: [Object: null prototype],
      _eventsCount: 12,
      devToolsWebContents: [Getter]
    }
  },
  window: BrowserWindow {
    setBounds: [Function (anonymous)],
    _events: [Object: null prototype] {
      blur: [Function (anonymous)],
      focus: [Array],
      show: [Function: visibilityChanged],
      hide: [Function: visibilityChanged],
      minimize: [Function: visibilityChanged],
      maximize: [Function: visibilityChanged],
      restore: [Function: visibilityChanged],
      'new-tab': [Array],
      resize: [Function: stateChangeHandler],
      move: [Function: stateChangeHandler],
      close: [Function: closeHandler],
      closed: [Array]
    },
    _eventsCount: 12,
    devToolsWebContents: [Getter]
  }
}
mainWindow.focus
sendParamsOnDidFinishLoad.window.webContents.did-finish-load https://www.npmjs.com/
sendParamsOnDidFinishLoad.window.webContents.did-finish-load https://www.npmjs.com/
app.quit {
  event: {
    preventDefault: [Function: preventDefault],
    sender: App {
      quit: [Function: quit],
      exit: [Function: exit],
      focus: [Function: focus],
      getVersion: [Function: getVersion],
      setVersion: [Function: setVersion],
      getName: [Function: getName],
      setName: [Function: setName],
      isReady: [Function: isReady],
      whenReady: [Function: whenReady],
      addRecentDocument: [Function: addRecentDocument],
      clearRecentDocuments: [Function: clearRecentDocuments],
      setAppUserModelId: [Function: setAppUserModelId],
      isDefaultProtocolClient: [Function: isDefaultProtocolClient],
      setAsDefaultProtocolClient: [Function: setAsDefaultProtocolClient],
      removeAsDefaultProtocolClient: [Function: removeAsDefaultProtocolClient],
      getApplicationNameForProtocol: [Function: getApplicationNameForProtocol],
      setBadgeCount: [Function: setBadgeCount],
      getBadgeCount: [Function: getBadgeCount],
      getLoginItemSettings: [Function: getLoginItemSettings],
      setLoginItemSettings: [Function: setLoginItemSettings],
      isEmojiPanelSupported: [Function: isEmojiPanelSupported],
      setAboutPanelOptions: [Function: setAboutPanelOptions],
      showAboutPanel: [Function: showAboutPanel],
      isUnityRunning: [Function: isUnityRunning],
      setAppPath: [Function: setAppPath],
      getAppPath: [Function: getAppPath],
      setPath: [Function: setPath],
      getPath: [Function: getPath],
      setAppLogsPath: [Function: setAppLogsPath],
      setDesktopName: [Function: setDesktopName],
      getLocale: [Function: getLocale],
      getLocaleCountryCode: [Function: getLocaleCountryCode],
      importCertificate: [Function: importCertificate],
      hasSingleInstanceLock: [Function: hasSingleInstanceLock],
      requestSingleInstanceLock: [Function: requestSingleInstanceLock],
      releaseSingleInstanceLock: [Function: releaseSingleInstanceLock],
      relaunch: [Function: relaunch],
      isAccessibilitySupportEnabled: [Function: isAccessibilitySupportEnabled],
      setAccessibilitySupportEnabled: [Function: setAccessibilitySupportEnabled],
      disableHardwareAcceleration: [Function: disableHardwareAcceleration],
      disableDomainBlockingFor3DAPIs: [Function: disableDomainBlockingFor3DAPIs],
      getFileIcon: [Function: getFileIcon],
      getAppMetrics: [Function (anonymous)],
      getGPUFeatureStatus: [Function: getGPUFeatureStatus],
      getGPUInfo: [Function: getGPUInfo],
      userAgentFallback: [Getter/Setter],
      enableSandbox: [Function: enableSandbox],
      allowRendererProcessReuse: [Getter/Setter],
      commandLine: [Object],
      isPackaged: true,
      _setDefaultAppPaths: [Function (anonymous)],
      _events: [Object: null prototype],
      _eventsCount: 17
    }
  },
  exitCode: 0
}
```
</details>

**Expected behavior**

Nativefier with option `tray` should consume one icon worth of tray area space

**Actual behavior**

Nativefier with option `tray` consumes all the available tray area space (and more, hiding other icons)

**Debug info**

- Console logs of your `nativefier` build command, with `--verbose` flag
- In-app DevTools console logs: nothing special in here
- Error messages: none
- Screenshots
    - Systray area before running the nativefier app with tray: 
    ![screenshot_tray-looking-normal_2021-06-22-08:38:06](https://user-images.githubusercontent.com/522085/122925940-548a2880-d335-11eb-9b65-f2094f93b0eb.png)
    - Systray area after running the nativefier app with tray: 
    ![screenshot_broken-tray-icon-gnome_2021-06-22-08:36:03](https://user-images.githubusercontent.com/522085/122925564-f3faeb80-d334-11eb-921b-fbbfe59d511c.png)

**Context**

 - Nativefier: master @ a491e3496675d7eef302ce2458332d0ef434b507
 - Node.js: 16.3.0
 - Npm: 7.17.0
 - OS: Arch Linux, up-to-date
 - Is it a regression? If yes, what's the last working / first broken version? Yes / dunno yet
 - GNOME Shell 40.2, gnome-shell-extension-appindicator 37

**Comment by ronjouch** [comment]
No longer an issue. Unsure where in the stack the bug resided. Whatever; closing, will re-open if I encounter it again
