### ISSUE TITLE
Error when attempting to reset zoom

### ISSUE THREAD

**Issue by Omoeba** [nativefier/nativefier#1241]
**Homework**

- [x] I looked at `nativefier --help` and https://github.com/nativefier/nativefier/blob/master/API.md
- [x] I checked the [Troubleshooting section of the README](https://github.com/nativefier/nativefier/blob/master/README.md#troubleshooting).
- [x] I searched existing issues, open & closed. Yes, my bug is new.
- [x] I'm using the latest version available at https://github.com/nativefier/nativefier/releases

**Bug description**

`cmd-0` doesn't reset the zoom as it should and throws an error.

**Steps to reproduce**

Give your ***full*** nativefier command and its logs, with the ***`--verbose` flag***, on a ***public*** site:

```
nativefier 'https://discord.com/app' --enable-es3-apis --icon discord.icns --portable --zoom 1 --verbose
```

**Expected behavior**

`cmd-0` successfully resets the zoom level

**Actual behavior**

the app throws an error and the zoom level is unchanged

**Debug info**

- Console logs of your `nativefier` build command, with `--verbose` flag
```
Running in verbose mode! This will produce a mountain of logs and is recommended only for troubleshooting or if you like Shakespeare.
Inferred platform darwin
Building app as portable. SECURITY WARNING: all data accumulated in the app folder after running it (including login information, cache, cookies) will be saved in the app folder. If this app is then shared with others, THEY WILL HAVE THAT ACCUMULATED DATA, POTENTIALLY INCLUDING ACCESS TO ANY ACCOUNTS YOU LOGGED INTO.

Performing async options post-processing.
Got icon from options. Using it, no inferring needed
Inferring name for https://discord.com/app
Fetched 4.4 kb page at https://discord.com/app
Inferred title: Discord
Sanitized filename for Discord : Discord
options {
  packager: {
    appCopyright: undefined,
    appVersion: undefined,
    arch: 'arm64',
    asar: false,
    buildVersion: undefined,
    darwinDarkModeSupport: false,
    dir: '/opt/homebrew/Cellar/nativefier/44.0.4/libexec/lib/node_modules/nativefier/app',
    electronVersion: '12.0.11',
    icon: 'discord.icns',
    name: 'Discord',
    out: '/Users/test',
    overwrite: true,
    platform: 'darwin',
    portable: true,
    targetUrl: 'https://discord.com/app',
    tmpdir: false,
    upgrade: false,
    upgradeFrom: undefined,
    win32metadata: {
      ProductName: undefined,
      InternalName: undefined,
      FileDescription: undefined
    }
  },
  nativefier: {
    accessibilityPrompt: true,
    alwaysOnTop: false,
    backgroundColor: undefined,
    basicAuthPassword: undefined,
    basicAuthUsername: undefined,
    blockExternalUrls: false,
    bookmarksMenu: undefined,
    bounce: false,
    browserwindowOptions: undefined,
    clearCache: false,
    counter: false,
    crashReporter: undefined,
    disableContextMenu: false,
    disableDevTools: false,
    disableGpu: false,
    diskCacheSize: undefined,
    disableOldBuildWarning: false,
    enableEs3Apis: true,
    fastQuit: false,
    fileDownloadOptions: undefined,
    flashPluginDir: undefined,
    fullScreen: false,
    globalShortcuts: undefined,
    hideWindowFrame: false,
    ignoreCertificate: false,
    ignoreGpuBlacklist: false,
    inject: [],
    insecure: false,
    internalUrls: undefined,
    lang: undefined,
    maximize: false,
    nativefierVersion: '44.0.4',
    processEnvs: undefined,
    proxyRules: undefined,
    showMenuBar: false,
    singleInstance: false,
    titleBarStyle: undefined,
    tray: false,
    userAgent: undefined,
    userAgentHonest: false,
    verbose: true,
    versionString: undefined,
    width: 1280,
    height: 800,
    minWidth: undefined,
    minHeight: undefined,
    maxWidth: undefined,
    maxHeight: undefined,
    widevine: false,
    x: undefined,
    y: undefined,
    zoom: 1
  }
}

Preparing Electron app...
Copying electron app from /opt/homebrew/Cellar/nativefier/44.0.4/libexec/lib/node_modules/nativefier/app to /var/folders/6f/0yxp478n05ng7lb4fx2gfhxh0000gn/T/nativefier-23-12-17-app--21550-c2Viez13d7w7
Writing app config to /var/folders/6f/0yxp478n05ng7lb4fx2gfhxh0000gn/T/nativefier-23-12-17-app--21550-c2Viez13d7w7/nativefier.json
No files to inject, skipping copy.
Updating /var/folders/6f/0yxp478n05ng7lb4fx2gfhxh0000gn/T/nativefier-23-12-17-app--21550-c2Viez13d7w7/package.json 'name' field to discord-nativefier-18566a

Converting icons...
Building for macOS and icon is already a .icns, no conversion needed
Copying icons if necessary
No copying necessary on macOS; aborting

Packaging... This will take a few seconds, maybe minutes if the requested Electron isn't cached yet...

Finalizing build...
App built to /Users/test/Discord-darwin-arm64, move to wherever it makes sense for you and run the app bundle.
```
![image](https://user-images.githubusercontent.com/38597972/123127714-63d5a880-d3ff-11eb-8d16-01f2bb50bdfa.png)

`A JavaScript error occurred in the main process`

```
Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from undefined
at Object.set (electron/js2c/browser_init.js:161:13199)
at /Applications/Discord.app/Contents/Resources/app/lib/webpack:/nativefier-placeholder/src/helpers/windowHelpers.ts:334:41
at withFocusedWindow (/Applications/Discord.app/Contents/Resources/app/lib/webpack:/nativefier-placeholder/src/helpers/windowHelpers.ts:320:12)
at zoomReset (/Applications/Discord.app/Contents/Resources/app/lib/webpack:/nativefier-placeholder/src/helpers/windowHelpers.ts:333:3)
at MenuItem.click (electron/js2c/browser_init.js:73:1742)
at Object.a._executeCommand (electron/js2c/browser_init.js:81:2492)
```

**Context**

 - Nativefier: 44.0.4
 - Node.js: 16.3.0
 - Npm: 7.15.1
 - OS: Mac OS Big Sur 11.4
 - Additional context: The following is shown when the `View` menu is clicked
![image](https://user-images.githubusercontent.com/38597972/123128231-d21a6b00-d3ff-11eb-8589-e1355cfee483.png)
The issue occurs regardless of whether the `--portable` flag is included

**Comment by TheCleric** [comment]
Sorry about that. We'll get that resolved very soon!
