### ISSUE TITLE
CSS injection doesn’t seem to work for favro.com in macOS v45.0.0

### ISSUE THREAD

**Issue by champagnealexandre** [nativefier/nativefier#1264]
**Homework**

- [X] I looked at `nativefier --help` and https://github.com/nativefier/nativefier/blob/master/API.md
- [X] I checked the [Troubleshooting section of the README](https://github.com/nativefier/nativefier/blob/master/README.md#troubleshooting).
- [X] I searched existing issues, open & closed. Yes, my bug is new.
- [X] I'm using the latest version available at https://github.com/nativefier/nativefier/releases

**Bug description**

Can’t seem to inject CSS into favro.com. The exact same CSS code, injected in Chrome, works fine.

**Steps to reproduce**

Give your ***full*** nativefier command and its logs, with the ***`--verbose` flag***, on a ***public*** site:

```
[ 0 ] alexandre@Alexandres-MacBook-Pro Desktop nativefier https://favro.com/ --inject userstyle_favro.css --verbose
Running in verbose mode! This will produce a mountain of logs and is recommended only for troubleshooting or if you like Shakespeare.
Inferred platform darwin

Performing async options post-processing.
Inferring icon for https://favro.com/ on darwin
Inferring icon from store for https://favro.com/ on darwin
Allowed icon formats when building for darwin: [ '.icns', '.png', '.ico' ]
Inferring name for https://favro.com/
Got 249 icons from gitcloud
Max icon match score: 0
No relevant icon in store.
Trying to extract a .png icon from the page.
Fetched 61.1 kb page at https://favro.com/
Inferred title: Favro | The Agile Collaborative Planning App for SaaS &amp; Games
Sanitized filename for Favro | The Agile Collaborative Planning App for SaaS &amp; Games : Favro  The Agile Collaborative Planning App for SaaS &amp; Games
Got an icon from the page.
Writing 376.4 kb icon to /var/folders/_d/msvqcfz913l3gglp7npjns8r0000gn/T/nativefier-17-47-38-iconinfer--79211-0yWzm7Cf0BOp/icon.png
options {
  packager: {
    appCopyright: undefined,
    appVersion: undefined,
    arch: 'x64',
    asar: false,
    buildVersion: undefined,
    darwinDarkModeSupport: false,
    dir: '/usr/local/lib/node_modules/nativefier/app',
    electronVersion: '13.1.7',
    icon: '/var/folders/_d/msvqcfz913l3gglp7npjns8r0000gn/T/nativefier-17-47-38-iconinfer--79211-0yWzm7Cf0BOp/icon.png',
    name: 'Favro  The Agile Collaborative Planning App for SaaS &amp; Games',
    out: '/Users/alexandre/Desktop',
    overwrite: true,
    platform: 'darwin',
    portable: false,
    targetUrl: 'https://favro.com/',
    tmpdir: false,
    upgrade: false,
    upgradeFrom: undefined,
    win32metadata: {
      ProductName: undefined,
      InternalName: undefined,
      FileDescription: undefined
    }
  },
  nativefier: {
    accessibilityPrompt: true,
    alwaysOnTop: false,
    backgroundColor: undefined,
    basicAuthPassword: undefined,
    basicAuthUsername: undefined,
    blockExternalUrls: false,
    bookmarksMenu: undefined,
    bounce: false,
    browserwindowOptions: undefined,
    clearCache: false,
    counter: false,
    crashReporter: undefined,
    disableContextMenu: false,
    disableDevTools: false,
    disableGpu: false,
    diskCacheSize: undefined,
    disableOldBuildWarning: false,
    enableEs3Apis: false,
    fastQuit: false,
    fileDownloadOptions: undefined,
    flashPluginDir: undefined,
    fullScreen: false,
    globalShortcuts: undefined,
    hideWindowFrame: false,
    ignoreCertificate: false,
    ignoreGpuBlacklist: false,
    inject: [ 'userstyle_favro.css' ],
    insecure: false,
    internalUrls: undefined,
    lang: undefined,
    maximize: false,
    nativefierVersion: '45.0.0',
    processEnvs: undefined,
    proxyRules: undefined,
    showMenuBar: false,
    singleInstance: false,
    titleBarStyle: undefined,
    tray: 'false',
    userAgent: undefined,
    userAgentHonest: false,
    verbose: true,
    versionString: undefined,
    width: 1280,
    height: 800,
    minWidth: undefined,
    minHeight: undefined,
    maxWidth: undefined,
    maxHeight: undefined,
    widevine: false,
    x: undefined,
    y: undefined,
    zoom: 1
  }
}

Preparing Electron app...
Copying electron app from /usr/local/lib/node_modules/nativefier/app to /var/folders/_d/msvqcfz913l3gglp7npjns8r0000gn/T/nativefier-17-47-38-app--79211-3KctxWxTCt9p
Writing app config to /var/folders/_d/msvqcfz913l3gglp7npjns8r0000gn/T/nativefier-17-47-38-app--79211-3KctxWxTCt9p/nativefier.json
Copying 1 files to inject in app.
Copying injection file "userstyle_favro.css" to "/var/folders/_d/msvqcfz913l3gglp7npjns8r0000gn/T/nativefier-17-47-38-app--79211-3KctxWxTCt9p/inject/inject-22ccba.css"
Updating /var/folders/_d/msvqcfz913l3gglp7npjns8r0000gn/T/nativefier-17-47-38-app--79211-3KctxWxTCt9p/package.json 'name' field to favro--the-agile-collaborative-planning-app-for-saas-&amp;-games-nativefier-909c8f

Converting icons...
Converting icon /var/folders/_d/msvqcfz913l3gglp7npjns8r0000gn/T/nativefier-17-47-38-iconinfer--79211-0yWzm7Cf0BOp/icon.png to /var/folders/_d/msvqcfz913l3gglp7npjns8r0000gn/T/nativefier-17-47-38-iconconv--79211-musKd9Llxb03/icon.icns. Calling shell command: "/usr/local/lib/node_modules/nativefier/icon-scripts/convertToIcns" "/var/folders/_d/msvqcfz913l3gglp7npjns8r0000gn/T/nativefier-17-47-38-iconinfer--79211-0yWzm7Cf0BOp/icon.png" "/var/folders/_d/msvqcfz913l3gglp7npjns8r0000gn/T/nativefier-17-47-38-iconconv--79211-musKd9Llxb03/icon.icns"
Failed to convert icon to .icns, skipping. Error: Icon conversion failed with status code 1.
stdout:
stderr: mktemp: too few X's in template ‘nativefier_icons’

    at iconShellHelper (/usr/local/lib/node_modules/nativefier/src/helpers/iconShellHelpers.ts:46:11)
    at Object.convertToIcns (/usr/local/lib/node_modules/nativefier/src/helpers/iconShellHelpers.ts:83:10)
    at Object.convertIconIfNecessary (/usr/local/lib/node_modules/nativefier/src/build/buildIcon.ts:87:24)
    at Object.buildNativefierApp (/usr/local/lib/node_modules/nativefier/src/build/buildNativefierApp.ts:176:3)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
Copying icons if necessary
No icon specified in options; aborting

Packaging... This will take a few seconds, maybe minutes if the requested Electron isn't cached yet...
  electron-packager Electron Packager 15.3.0
  electron-packager Node v14.17.3
  electron-packager Host Operating system: darwin 20.5.0 (x64) +0ms
  electron-packager Packager Options: {"arch":"x64","asar":false,"darwinDarkModeSupport":false,"dir":"/var/folders/_d/msvqcfz913l3gglp7npjns8r0000gn/T/nativefier-17-47-38-app--79211-3KctxWxTCt9p","electronVersion":"13.1.7","name":"Favro  The Agile Collaborative Planning App for SaaS &amp; Games","out":"/Users/alexandre/Desktop","overwrite":true,"platform":"darwin","portable":false,"targetUrl":"https://favro.com/","tmpdir":false,"upgrade":false,"win32metadata":{}} +0ms
  electron-packager Target Platforms: darwin +1ms
  electron-packager Target Architectures: x64 +0ms
  electron-packager Inferring appVersion from version in /var/folders/_d/msvqcfz913l3gglp7npjns8r0000gn/T/nativefier-17-47-38-app--79211-3KctxWxTCt9p/package.json +0ms
  electron-packager Application name: Favro  The Agile Collaborative Planning App for SaaS &amp; Games +5ms
  electron-packager Target Electron version: 13.1.7 +0ms
  electron-packager Ignored path regular expressions: [
  '/package-lock\\.json$',
  '/yarn\\.lock$',
  '/\\.git($|/)',
  '/node_modules/\\.bin($|/)',
  '\\.o(bj)?$'
] +0ms
  electron-packager Downloading Electron with options {"platform":"darwin","arch":"x64","version":"13.1.7","artifactName":"electron"} +0ms
Packaging app for platform darwin x64 using electron v13.1.7
  electron-packager Creating /Users/alexandre/Desktop/darwin-x64-template +2ms
  electron-packager Extracting /Users/alexandre/Library/Caches/electron/c02b94db45d0f83639398d95d22e41e09fd3474003678b9f728c6d3f2a93193c/electron-v13.1.7-darwin-x64.zip to /Users/alexandre/Desktop/darwin-x64-template +1ms
  electron-packager Initializing app in /Users/alexandre/Desktop/Favro  The Agile Collaborative Planning App for SaaS &amp; Games-darwin-x64 from /Users/alexandre/Desktop/darwin-x64-template template +0ms
  electron-packager Ignored paths based on the out param: [
  '/Users/alexandre/Desktop/Favro  The Agile Collaborative Planning App for SaaS &amp; Games-darwin-x64',
  '/Users/alexandre/Desktop/Favro  The Agile Collaborative Planning App for SaaS &amp; Games-darwin-arm64',
  '/Users/alexandre/Desktop/Favro  The Agile Collaborative Planning App for SaaS &amp; Games-linux-ia32',
  '/Users/alexandre/Desktop/Favro  The Agile Collaborative Planning App for SaaS &amp; Games-linux-x64',
  '/Users/alexandre/Desktop/Favro  The Agile Collaborative Planning App for SaaS &amp; Games-linux-armv7l',
  '/Users/alexandre/Desktop/Favro  The Agile Collaborative Planning App for SaaS &amp; Games-linux-arm64',
  '/Users/alexandre/Desktop/Favro  The Agile Collaborative Planning App for SaaS &amp; Games-linux-mips64el',
  '/Users/alexandre/Desktop/Favro  The Agile Collaborative Planning App for SaaS &amp; Games-mas-x64',
  '/Users/alexandre/Desktop/Favro  The Agile Collaborative Planning App for SaaS &amp; Games-mas-arm64',
  '/Users/alexandre/Desktop/Favro  The Agile Collaborative Planning App for SaaS &amp; Games-win32-ia32',
  '/Users/alexandre/Desktop/Favro  The Agile Collaborative Planning App for SaaS &amp; Games-win32-x64',
  '/Users/alexandre/Desktop/Favro  The Agile Collaborative Planning App for SaaS &amp; Games-win32-arm64'
] +2s
  electron-packager Validating bundled Electron app +0ms
  electron-packager Checking for a package.json file +0ms
  electron-packager Checking for the main entry point file +0ms
  electron-packager Validation complete +1ms
  electron-packager Renaming Electron to Favro  The Agile Collaborative Planning App for SaaS &amp; Games in /Users/alexandre/Desktop/Favro  The Agile Collaborative Planning App for SaaS &amp; Games-darwin-x64/Electron.app/Contents/MacOS +40ms
  electron-packager Renaming Electron Helper to Favro  The Agile Collaborative Planning App for SaaS &amp; Games Helper in /Users/alexandre/Desktop/Favro  The Agile Collaborative Planning App for SaaS &amp; Games-darwin-x64/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS +0ms
  electron-packager Renaming Electron Helper (Renderer) to Favro  The Agile Collaborative Planning App for SaaS &amp; Games Helper (Renderer) in /Users/alexandre/Desktop/Favro  The Agile Collaborative Planning App for SaaS &amp; Games-darwin-x64/Electron.app/Contents/Frameworks/Electron Helper (Renderer).app/Contents/MacOS +1ms
  electron-packager Renaming Electron Helper (Plugin) to Favro  The Agile Collaborative Planning App for SaaS &amp; Games Helper (Plugin) in /Users/alexandre/Desktop/Favro  The Agile Collaborative Planning App for SaaS &amp; Games-darwin-x64/Electron.app/Contents/Frameworks/Electron Helper (Plugin).app/Contents/MacOS +0ms
  electron-packager Renaming Electron Helper (GPU) to Favro  The Agile Collaborative Planning App for SaaS &amp; Games Helper (GPU) in /Users/alexandre/Desktop/Favro  The Agile Collaborative Planning App for SaaS &amp; Games-darwin-x64/Electron.app/Contents/Frameworks/Electron Helper (GPU).app/Contents/MacOS +0ms
  electron-packager Renaming Electron Helper.app to Favro  The Agile Collaborative Planning App for SaaS &amp; Games Helper.app in /Users/alexandre/Desktop/Favro  The Agile Collaborative Planning App for SaaS &amp; Games-darwin-x64/Electron.app/Contents/Frameworks +0ms
  electron-packager Renaming Electron Helper (Renderer).app to Favro  The Agile Collaborative Planning App for SaaS &amp; Games Helper (Renderer).app in /Users/alexandre/Desktop/Favro  The Agile Collaborative Planning App for SaaS &amp; Games-darwin-x64/Electron.app/Contents/Frameworks +0ms
  electron-packager Renaming Electron Helper (Plugin).app to Favro  The Agile Collaborative Planning App for SaaS &amp; Games Helper (Plugin).app in /Users/alexandre/Desktop/Favro  The Agile Collaborative Planning App for SaaS &amp; Games-darwin-x64/Electron.app/Contents/Frameworks +0ms
  electron-packager Renaming Electron Helper (GPU).app to Favro  The Agile Collaborative Planning App for SaaS &amp; Games Helper (GPU).app in /Users/alexandre/Desktop/Favro  The Agile Collaborative Planning App for SaaS &amp; Games-darwin-x64/Electron.app/Contents/Frameworks +0ms

Finalizing build...
App built to /Users/alexandre/Desktop/Favro  The Agile Collaborative Planning App for SaaS &amp; Games-darwin-x64, move to wherever it makes sense for you and run the app bundle.
```

**Expected behavior**

Cosmetic changes to the website interface.

**Actual behavior**

Nothing seems to be applied :-(

**Context**

 - Nativefier: 45.0.0
 - Node.js: 14.17.3
 - OS: macOS big sur 11.4
 - Is it a regression? no

**Comment by champagnealexandre** [comment]
User error ; issue solved.

**Comment by ronjouch** [comment]
> User error ; issue solved.

@champagnealexandre thanks a lot for the follow-up and remember to close it.

Was this really 100% user error (like e.g. "my inject's CSS selector had a typo in it")? Is there anything Nativefier could have done to avoid it or make the mistake more noticeable / earlier?

**Comment by champagnealexandre** [comment]
For some reason, when using an injector plugin in Chrome it used to work, whereas with nativefier it requires the ``!important`` keyword at every property assignment — I’m new to CSS but I guess this has to do with loading order. Don’t think nativefier could have done anything for that!

**Comment by ronjouch** [comment]
> For some reason, when using an injector plugin in Chrome it used to work, whereas with nativefier it requires the `!important` keyword at every property assignment — I’m new to CSS but I guess this has to do with loading order. Don’t think nativefier could have done anything for that!

@champagnealexandre true. Added to API.md documentation in 33f2931. Thanks!
