### ISSUE TITLE
No `widevine` support for armv7l

### ISSUE THREAD

**Issue by cycool29** [nativefier/nativefier#1285]
**Homework**

- [x] I looked at `nativefier --help` and https://github.com/nativefier/nativefier/blob/master/API.md
- [x] I checked the [Troubleshooting section of the README](https://github.com/nativefier/nativefier/blob/master/README.md#troubleshooting).
- [x] I searched existing issues, open & closed. Yes, my bug is new.
- [x] I'm using the latest version available at https://github.com/nativefier/nativefier/releases

**Bug description**

When natifying `open.spotify.com`, `--widevine` argument throws a 404 error.
After investigating, found that `--widevine` is not available for armv7l architechture.

**Steps to reproduce**

```
nativefier 'https://open.spotify.com/' --verbose --widevine  --inject spotify.js  --inject spotify.css --user-agent firefox -n "Spotify" -a armv7l

Running in verbose mode! This will produce a mountain of logs and is recommended only for troubleshooting or if you like Shakespeare.

ATTENTION: Using the **unofficial** Electron from castLabs 
It implements Google's Widevine Content Decryption Module (CDM) for DRM-enabled playback. 
Simply abort & re-run without passing the widevine flag to default to 13.1.7-wvvmp
Inferred platform linux

Performing async options post-processing.
Grabbing Firefox version data from https://product-details.mozilla.org/1.0/firefox_versions.json
Inferring icon for https://open.spotify.com/ on linux
Inferring icon from store for https://open.spotify.com/ on linux
Allowed icon formats when building for linux: [ '.png', '.ico' ]
Sanitized filename for Spotify : Spotify
Got 246 icons from gitcloud
Max icon match score: 0
No relevant icon in store.
Trying to extract a .png icon from the page.
Got latest Firefox version 92.0.1
Got an icon from the page.
Writing 249.1 kb icon to /tmp/nativefier-22-21-58-iconinfer--10556-pAz61uyn3TXj/icon.png
options {
  packager: {
    appCopyright: undefined,
    appVersion: undefined,
    arch: 'armv7l',
    asar: false,
    buildVersion: undefined,
    darwinDarkModeSupport: false,
    dir: '/usr/local/lib/node_modules/nativefier/app',
    electronVersion: '13.1.7-wvvmp',
    icon: '/tmp/nativefier-22-21-58-iconinfer--10556-pAz61uyn3TXj/icon.png',
    name: 'Spotify',
    out: '/home/pi',
    overwrite: true,
    platform: 'linux',
    portable: false,
    targetUrl: 'https://open.spotify.com/',
    tmpdir: false,
    upgrade: false,
    upgradeFrom: undefined,
    win32metadata: {
      ProductName: 'Spotify',
      InternalName: 'Spotify',
      FileDescription: 'Spotify'
    }
  },
  nativefier: {
    accessibilityPrompt: true,
    alwaysOnTop: false,
    backgroundColor: undefined,
    basicAuthPassword: undefined,
    basicAuthUsername: undefined,
    blockExternalUrls: false,
    bookmarksMenu: undefined,
    bounce: false,
    browserwindowOptions: undefined,
    clearCache: false,
    counter: false,
    crashReporter: undefined,
    disableContextMenu: false,
    disableDevTools: false,
    disableGpu: false,
    diskCacheSize: undefined,
    disableOldBuildWarning: false,
    enableEs3Apis: false,
    fastQuit: false,
    fileDownloadOptions: undefined,
    flashPluginDir: undefined,
    fullScreen: false,
    globalShortcuts: undefined,
    hideWindowFrame: false,
    ignoreCertificate: false,
    ignoreGpuBlacklist: false,
    inject: [ 'spotify.js', 'spotify.css' ],
    insecure: false,
    internalUrls: undefined,
    lang: undefined,
    maximize: false,
    nativefierVersion: '45.0.0',
    processEnvs: undefined,
    proxyRules: undefined,
    showMenuBar: false,
    singleInstance: false,
    titleBarStyle: undefined,
    tray: 'false',
    userAgent: 'Mozilla/5.0 (X11; Linux x86_64; rv:92.0.1) Gecko/20100101 Firefox/92.0.1',
    userAgentHonest: false,
    verbose: true,
    versionString: undefined,
    width: 1280,
    height: 800,
    minWidth: undefined,
    minHeight: undefined,
    maxWidth: undefined,
    maxHeight: undefined,
    widevine: true,
    x: undefined,
    y: undefined,
    zoom: 1
  }
}

Preparing Electron app...
Copying electron app from /usr/local/lib/node_modules/nativefier/app to /tmp/nativefier-22-21-58-app--10556-r5QIi2y0sd21
Writing app config to /tmp/nativefier-22-21-58-app--10556-r5QIi2y0sd21/nativefier.json
Copying 2 files to inject in app.
Copying injection file "spotify.js" to "/tmp/nativefier-22-21-58-app--10556-r5QIi2y0sd21/inject/inject-ad9296.js"
Copying injection file "spotify.css" to "/tmp/nativefier-22-21-58-app--10556-r5QIi2y0sd21/inject/inject-0381bf.css"
Updating /tmp/nativefier-22-21-58-app--10556-r5QIi2y0sd21/package.json 'name' field to spotify-nativefier-437e3b

Converting icons...
Building for Linux and icon is already a .png, no conversion needed
Copying icons if necessary
Copying icon /tmp/nativefier-22-21-58-iconinfer--10556-pAz61uyn3TXj/icon.png to /tmp/nativefier-22-21-58-app--10556-r5QIi2y0sd21/icon.png

Packaging... This will take a few seconds, maybe minutes if the requested Electron isn't cached yet...
  electron-packager Electron Packager 15.3.0
  electron-packager Node v16.9.1
  electron-packager Host Operating system: linux 5.10.60-v7l+ (arm) +0ms
  electron-packager Packager Options: {"arch":"armv7l","asar":false,"darwinDarkModeSupport":false,"dir":"/tmp/nativefier-22-21-58-app--10556-r5QIi2y0sd21","electronVersion":"13.1.7-wvvmp","icon":"/tmp/nativefier-22-21-58-iconinfer--10556-pAz61uyn3TXj/icon.png","name":"Spotify","out":"/home/pi","overwrite":true,"platform":"linux","portable":false,"targetUrl":"https://open.spotify.com/","tmpdir":false,"upgrade":false,"win32metadata":{"ProductName":"Spotify","InternalName":"Spotify","FileDescription":"Spotify"}} +1ms
  electron-packager Target Platforms: linux +1ms
  electron-packager Target Architectures: armv7l +0ms
  electron-packager Inferring appVersion from version in /tmp/nativefier-22-21-58-app--10556-r5QIi2y0sd21/package.json +0ms
  electron-packager Application name: Spotify +13ms
  electron-packager Target Electron version: 13.1.7-wvvmp +0ms
  electron-packager Ignored path regular expressions: [
  '/package-lock\\.json$',
  '/yarn\\.lock$',
  '/\\.git($|/)',
  '/node_modules/\\.bin($|/)',
  '\\.o(bj)?$',
  '/tmp/electron-packager'
] +0ms
  electron-packager Downloading Electron with options {"platform":"linux","arch":"armv7l","version":"13.1.7-wvvmp","artifactName":"electron"} +0ms
Error during build. Run with --verbose for details. GotError [HTTPError]: Response code 404 (Not Found) for https://github.com/castlabs/electron-releases/releases/download/v13.1.7-wvvmp/electron-v13.1.7-wvvmp-linux-armv7l.zip
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/nativefier/node_modules/got/source/as-stream.js:35:24)
    at EventEmitter.emit (node:events:394:28)
    at EventEmitter.emit (node:domain:475:12)
    at module.exports (/usr/local/lib/node_modules/nativefier/node_modules/got/source/get-response.js:22:10)
    at ClientRequest.handleResponse (/usr/local/lib/node_modules/nativefier/node_modules/got/source/request-as-event-emitter.js:155:5)
    at Object.onceWrapper (node:events:514:26)
    at ClientRequest.emit (node:events:406:35)
    at ClientRequest.emit (node:domain:475:12)
    at ClientRequest.origin.emit (/usr/local/lib/node_modules/nativefier/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:621:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
    at TLSSocket.socketOnData (node:_http_client:487:22)
    at TLSSocket.emit (node:events:394:28)
    at TLSSocket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9) {
  host: 'github.com',
  hostname: 'github.com',
  method: 'GET',
  path: '/castlabs/electron-releases/releases/download/v13.1.7-wvvmp/electron-v13.1.7-wvvmp-linux-armv7l.zip',
  socketPath: undefined,
  protocol: 'https:',
  url: 'https://github.com/castlabs/electron-releases/releases/download/v13.1.7-wvvmp/electron-v13.1.7-wvvmp-linux-armv7l.zip',
  gotOptions: {
    path: '/castlabs/electron-releases/releases/download/v13.1.7-wvvmp/electron-v13.1.7-wvvmp-linux-armv7l.zip',
    protocol: 'https:',
    slashes: true,
    auth: null,
    host: 'github.com',
    port: null,
    hostname: 'github.com',
    hash: null,
    search: null,
    query: null,
    pathname: '/castlabs/electron-releases/releases/download/v13.1.7-wvvmp/electron-v13.1.7-wvvmp-linux-armv7l.zip',
    href: 'https://github.com/castlabs/electron-releases/releases/download/v13.1.7-wvvmp/electron-v13.1.7-wvvmp-linux-armv7l.zip',
    retry: {
      retries: [Function (anonymous)],
      methods: [Set],
      statusCodes: [Set],
      errorCodes: [Set]
    },
    headers: {
      'user-agent': 'got/9.6.0 (https://github.com/sindresorhus/got)',
      'accept-encoding': 'gzip, deflate'
    },
    hooks: {
      beforeRequest: [],
      beforeRedirect: [],
      beforeRetry: [],
      afterResponse: [],
      beforeError: [],
      init: []
    },
    decompress: true,
    throwHttpErrors: true,
    followRedirect: true,
    stream: true,
    form: false,
    json: false,
    cache: false,
    useElectronNet: false,
    method: 'GET'
  },
  statusCode: 404,
  statusMessage: 'Not Found',
  headers: {
    server: 'GitHub.com',
    date: 'Sat, 25 Sep 2021 14:22:03 GMT',
    'content-type': 'text/plain; charset=utf-8',
    vary: 'X-PJAX, X-PJAX-Container, Accept-Encoding, Accept, X-Requested-With',
    'permissions-policy': 'interest-cohort=()',
    'cache-control': 'no-cache',
    'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
    'x-frame-options': 'deny',
    'x-content-type-options': 'nosniff',
    'x-xss-protection': '0',
    'referrer-policy': 'no-referrer-when-downgrade',
    'expect-ct': 'max-age=2592000, report-uri="https://api.github.com/_private/browser/errors"',
    'content-security-policy': "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
    'content-encoding': 'gzip',
    'transfer-encoding': 'chunked',
    'x-github-request-id': 'A49C:7CAC:210C24:2C8E47:614F308B',
    connection: 'close'
  },
  body: undefined
}


```
Then, it just hang there.

**Expected behavior**

Natifying spotify web player, without error.

**Actual behavior**

The command throws an error, seems like the electron link is incorrect.
Checked in https://github.com/castlabs/electron-releases/releases/tag/v13.1.7-wvvmp , **no armv7l support.**

**Reference**
https://github.com/castlabs/electron-releases/issues/23
https://github.com/castlabs/electron-releases/issues/41

**Debug info**

Same as `Step to reproduce`.

**Context**

 - Nativefier: `45.0.0`
 - Node.js: `v16.9.1`
 - Npm: `7.21.1`
 - OS: `Raspbian GNU/Linux 10 (buster)`
 - Is it a regression? None
 - Additional context: None

**Comment by TheCleric** [comment]
Unfortunately not fixable on our end until castlabs supports that architecture. Bestselling  we could do is add an error message before it gets to the failure point indicating that this is an unsupported configuration.

**Comment by cycool29** [comment]
> Bestselling we could do is add an error message before it gets to the failure point indicating that this is an unsupported configuration. 

Ya, I think that will be better then just put the 404 error to the user.

**Comment by cycool29** [comment]
May I know how is the progress now? @TheCleric

**Comment by TheCleric** [comment]
> May I know how is the progress now? @TheCleric

It is not something I am actively working on, but a PR from the community is always welcome.
