### ISSUE TITLE
app name with Chinese character not displayed correctly

### ISSUE THREAD

**Issue by everyx** [nativefier/nativefier#1332]
**Homework**

- [x] I looked at `nativefier --help` and https://github.com/nativefier/nativefier/blob/master/API.md
- [x] I checked the [Troubleshooting section of the README](https://github.com/nativefier/nativefier/blob/master/README.md#troubleshooting).
- [x] I searched existing issues, open & closed. Yes, my bug is new.
- [x] I'm using the latest version available at https://github.com/nativefier/nativefier/releases

**Bug description**

app name with Chinese character display garbled on Linux/Gnome41.2 as below, the correct should be "滴答清单-nativefier-xxxxx"

Below is left of top bar of Gnome when app activated:
![left of top bar of Gnome when app activated](https://user-images.githubusercontent.com/1665522/146626169-a312f89e-94c7-4752-a1fb-adce1eaf6f8f.png)

Below is app switch bar of Gnome
![app switch bar of Gnome](https://user-images.githubusercontent.com/1665522/146626238-069f6b1d-636e-45c3-8a21-c1be156f43ea.png)

**Steps to reproduce**

I use this command to convert a website for my ArchLinux system, nativefier command is below with logs:

```shell
nativefier \
        --name "滴答清单" \
        --width "800px" \
        --height "600px" \
        --user-agent "Mozilla/5.0 (X11; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0" \
        --verbose \
        --single-instance \
        --disable-dev-tools \
        --tray \
        https://dida365.com/signin
Running in verbose mode! This will produce a mountain of logs and is recommended only for troubleshooting or if you like Shakespeare.


    Hi! Nativefier is minimally maintained these days, and needs more hands.
    If you have the time & motivation, help with bugfixes and maintenance is VERY welcome.
    Please go to https://github.com/nativefier/nativefier and help how you can. Thanks.



Processing options...
rawOptions {
  _: [ 'https://dida365.com/signin' ],
  name: '滴答清单',
  n: '滴答清单',
  width: NaN,
  height: NaN,
  'user-agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0',
  u: 'Mozilla/5.0 (X11; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0',
  userAgent: 'Mozilla/5.0 (X11; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0',
  verbose: true,
  'single-instance': true,
  singleInstance: true,
  'disable-dev-tools': true,
  disableDevTools: true,
  tray: 'true',
  c: false,
  conceal: false,
  'no-overwrite': false,
  noOverwrite: false,
  overwrite: true,
  portable: false,
  widevine: false,
  'always-on-top': false,
  alwaysOnTop: false,
  'disable-context-menu': false,
  disableContextMenu: false,
  'full-screen': false,
  fullScreen: false,
  'hide-window-frame': false,
  hideWindowFrame: false,
  m: false,
  'show-menu-bar': false,
  showMenuBar: false,
  maximize: false,
  zoom: 1,
  'user-agent-honest': false,
  honest: false,
  userAgentHonest: false,
  'clear-cache': false,
  clearCache: false,
  'block-external-urls': false,
  blockExternalUrls: false,
  'disable-gpu': false,
  disableGpu: false,
  'enable-es3-apis': false,
  enableEs3Apis: false,
  'ignore-gpu-blacklist': false,
  ignoreGpuBlacklist: false,
  'disable-old-build-warning-yesiknowitisinsecure': false,
  disableOldBuildWarningYesiknowitisinsecure: false,
  'ignore-certificate': false,
  ignoreCertificate: false,
  insecure: false,
  flash: false,
  bounce: false,
  counter: false,
  'darwin-dark-mode-support': false,
  darwinDarkModeSupport: false,
  f: false,
  'fast-quit': false,
  fastQuit: false,
  '$0': 'nativefier',
  targetUrl: 'https://dida365.com/signin',
  out: undefined
}
Inferred arch x64
Normalized URL https://dida365.com/signin to: https://dida365.com/signin
Running in verbose mode! This will produce a mountain of logs and is recommended only for troubleshooting or if you like Shakespeare.
Inferred platform linux

Performing async options post-processing.
mozilla/5.0 (x11; linux x86_64; rv:88.0) gecko/20100101 firefox/88.0 not found in [ 'edge', 'firefox', 'safari' ]
Inferring icon for https://dida365.com/signin on linux
Inferring icon from store for https://dida365.com/signin on linux
Allowed icon formats when building for linux: [ '.png', '.ico' ]
Sanitized filename for 滴答清单 : 滴答清单
Got 246 icons from gitcloud
Max icon match score: 0
No relevant icon in store.
Trying to extract a .png icon from the page.
Cannot automatically retrieve the app icon: Error: Request failed with status code 401
    at createError (/usr/lib/node_modules/nativefier/node_modules/page-icon/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/lib/node_modules/nativefier/node_modules/page-icon/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/usr/lib/node_modules/nativefier/node_modules/page-icon/node_modules/axios/lib/adapters/http.js:269:11)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  config: {
    url: 'https://dida365.com/apple-touch-icon.png',
    method: 'get',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'axios/0.21.4',
      host: 'dida365.com'
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    responseType: 'arraybuffer',
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    data: undefined
  },
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      connect: [Function (anonymous)],
      error: [Function (anonymous)],
      socket: [Function (anonymous)],
      timeout: [Function (anonymous)],
      prefinish: [Function: requestOnPrefinish]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: false,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    maxRequestsOnConnectionReached: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: false,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    _contentLength: 0,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    _closed: false,
    socket: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: null,
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      parser: null,
      _httpMessage: [Circular *1],
      [Symbol(async_id_symbol)]: 69,
      [Symbol(kHandle)]: [TCP],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(RequestTimeout)]: undefined
    },
    _header: 'GET https://dida365.com/apple-touch-icon.png HTTP/1.1\r\n' +
      'Accept: application/json, text/plain, */*\r\n' +
      'User-Agent: axios/0.21.4\r\n' +
      'host: dida365.com\r\n' +
      'Connection: close\r\n' +
      '\r\n',
    _keepAliveTimeout: 0,
    _onPendingData: [Function: nop],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 80,
      protocol: 'http:',
      options: [Object: null prototype],
      requests: [Object: null prototype] {},
      sockets: [Object: null prototype],
      freeSockets: [Object: null prototype] {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 1,
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'GET',
    maxHeaderSize: undefined,
    insecureHTTPParser: undefined,
    path: 'https://dida365.com/apple-touch-icon.png',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      socket: [Socket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      rawHeaders: [Array],
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 401,
      statusMessage: 'Unauthorized',
      client: [Socket],
      _consuming: false,
      _dumped: false,
      req: [Circular *1],
      responseUrl: 'http://127.0.0.1:1080/https://dida365.com/apple-touch-icon.png',
      redirects: [],
      [Symbol(kCapture)]: false,
      [Symbol(kHeaders)]: [Object],
      [Symbol(kHeadersCount)]: 40,
      [Symbol(kTrailers)]: null,
      [Symbol(kTrailersCount)]: 0,
      [Symbol(RequestTimeout)]: undefined
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: '127.0.0.1',
    protocol: 'http:',
    _redirectable: Writable {
      _writableState: [WritableState],
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 0,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [Circular *1],
      _currentUrl: 'http://127.0.0.1:1080/https://dida365.com/apple-touch-icon.png',
      [Symbol(kCapture)]: false
    },
    [Symbol(kCapture)]: false,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'user-agent': [Array],
      host: [Array]
    }
  },
  response: {
    status: 401,
    statusText: 'Unauthorized',
    headers: {
      connection: 'close',
      'content-length': '104',
      'access-control-allow-credentials': 'true',
      'cache-control': 'no-cache, no-store, max-age=0, must-revalidate',
      'content-type': 'application/octet-stream',
      date: 'Sat, 18 Dec 2021 02:40:10 GMT',
      etag: 'W/"68-6DlaAYGRr9CMIo1VtXw3aMuspiU"',
      expires: '0',
      pragma: 'no-cache',
      'set-cookie': [Array],
      'strict-transport-security': 'max-age=15552000; includeSubDomains',
      vary: 'Origin, Access-Control-Request-Method, Access-Control-Request-Headers',
      'x-content-type-options': 'nosniff',
      'x-dns-prefetch-control': 'off',
      'x-download-options': 'noopen',
      'x-frame-options': 'DENY',
      'x-xss-protection': '1; mode=block'
    },
    config: {
      url: 'https://dida365.com/apple-touch-icon.png',
      method: 'get',
      headers: [Object],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      adapter: [Function: httpAdapter],
      responseType: 'arraybuffer',
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      validateStatus: [Function: validateStatus],
      transitional: [Object],
      data: undefined
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [Socket],
      _header: 'GET https://dida365.com/apple-touch-icon.png HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: axios/0.21.4\r\n' +
        'host: dida365.com\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: 'https://dida365.com/apple-touch-icon.png',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: '127.0.0.1',
      protocol: 'http:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    data: <Buffer 7b 22 65 72 72 6f 72 49 64 22 3a 22 61 6d 71 68 61 66 37 7a 40 63 74 77 34 22 2c 22 65 72 72 6f 72 43 6f 64 65 22 3a 22 75 73 65 72 5f 6e 6f 74 5f 73 ... 54 more bytes>
  },
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
options {
  packager: {
    appCopyright: undefined,
    appVersion: undefined,
    arch: 'x64',
    asar: false,
    buildVersion: undefined,
    darwinDarkModeSupport: false,
    dir: '/usr/lib/node_modules/nativefier/app',
    electronVersion: '13.6.3',
    icon: undefined,
    name: '滴答清单',
    out: '/home/everyx/Downloads',
    overwrite: true,
    platform: 'linux',
    portable: false,
    targetUrl: 'https://dida365.com/signin',
    tmpdir: false,
    upgrade: false,
    upgradeFrom: undefined,
    win32metadata: {
      ProductName: '滴答清单',
      InternalName: '滴答清单',
      FileDescription: '滴答清单'
    }
  },
  nativefier: {
    accessibilityPrompt: true,
    alwaysOnTop: false,
    backgroundColor: undefined,
    basicAuthPassword: undefined,
    basicAuthUsername: undefined,
    blockExternalUrls: false,
    bookmarksMenu: undefined,
    bounce: false,
    browserwindowOptions: undefined,
    clearCache: false,
    counter: false,
    crashReporter: undefined,
    disableContextMenu: false,
    disableDevTools: true,
    disableGpu: false,
    diskCacheSize: undefined,
    disableOldBuildWarning: false,
    enableEs3Apis: false,
    fastQuit: false,
    fileDownloadOptions: undefined,
    flashPluginDir: undefined,
    fullScreen: false,
    globalShortcuts: undefined,
    hideWindowFrame: false,
    ignoreCertificate: false,
    ignoreGpuBlacklist: false,
    inject: [],
    insecure: false,
    internalUrls: undefined,
    lang: undefined,
    maximize: false,
    nativefierVersion: '45.0.8',
    processEnvs: undefined,
    proxyRules: undefined,
    showMenuBar: false,
    singleInstance: true,
    titleBarStyle: undefined,
    tray: 'true',
    userAgent: 'Mozilla/5.0 (X11; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0',
    userAgentHonest: false,
    verbose: true,
    versionString: undefined,
    width: NaN,
    height: NaN,
    minWidth: undefined,
    minHeight: undefined,
    maxWidth: undefined,
    maxHeight: undefined,
    widevine: false,
    x: undefined,
    y: undefined,
    zoom: 1
  }
}

Preparing Electron app...
Copying electron app from /usr/lib/node_modules/nativefier/app to /tmp/nativefier-10-40-9-app--6218-MBz0aUcMHiV7
Writing app config to /tmp/nativefier-10-40-9-app--6218-MBz0aUcMHiV7/nativefier.json {
  accessibilityPrompt: true,
  alwaysOnTop: false,
  appBundleId: undefined,
  appCategoryType: undefined,
  appCopyright: undefined,
  appVersion: undefined,
  arch: 'x64',
  asar: false,
  backgroundColor: undefined,
  basicAuthPassword: undefined,
  basicAuthUsername: undefined,
  blockExternalUrls: false,
  bounce: false,
  browserwindowOptions: undefined,
  buildDate: 1639795210811,
  buildVersion: undefined,
  clearCache: false,
  counter: false,
  crashReporter: undefined,
  darwinDarkModeSupport: false,
  derefSymlinks: undefined,
  disableContextMenu: false,
  disableDevTools: true,
  disableGpu: false,
  disableOldBuildWarning: false,
  diskCacheSize: undefined,
  download: undefined,
  electronVersionUsed: '13.6.3',
  enableEs3Apis: false,
  executableName: undefined,
  fastQuit: false,
  fileDownloadOptions: undefined,
  flashPluginDir: undefined,
  fullScreen: false,
  globalShortcuts: undefined,
  height: NaN,
  helperBundleId: undefined,
  hideWindowFrame: false,
  ignoreCertificate: false,
  ignoreGpuBlacklist: false,
  insecure: false,
  internalUrls: undefined,
  isUpgrade: false,
  junk: undefined,
  lang: undefined,
  maximize: false,
  maxHeight: undefined,
  maxWidth: undefined,
  minHeight: undefined,
  minWidth: undefined,
  name: '滴答清单',
  nativefierVersion: '45.0.8',
  osxNotarize: undefined,
  osxSign: undefined,
  portable: false,
  processEnvs: undefined,
  protocols: undefined,
  proxyRules: undefined,
  prune: undefined,
  quiet: undefined,
  showMenuBar: false,
  singleInstance: true,
  targetUrl: 'https://dida365.com/signin',
  titleBarStyle: undefined,
  tray: 'true',
  usageDescription: undefined,
  userAgent: 'Mozilla/5.0 (X11; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0',
  userAgentHonest: false,
  versionString: undefined,
  width: NaN,
  widevine: false,
  win32metadata: {
    ProductName: '滴答清单',
    InternalName: '滴答清单',
    FileDescription: '滴答清单'
  },
  x: undefined,
  y: undefined,
  zoom: 1,
  oldBuildWarningText: ''
}
No files to inject, skipping copy.
Updating /tmp/nativefier-10-40-9-app--6218-MBz0aUcMHiV7/package.json 'name' field to 滴答清单-nativefier-31f689

Converting icons...
Option "icon" not set, skipping icon conversion.
Copying icons if necessary
No icon specified in options; aborting

Packaging... This will take a few seconds, maybe minutes if the requested Electron isn't cached yet...
  electron-packager Electron Packager 15.4.0
  electron-packager Node v17.2.0
  electron-packager Host Operating system: linux 5.15.10-arch1-1 (x64) +0ms
  electron-packager Packager Options: {"arch":"x64","asar":false,"darwinDarkModeSupport":false,"dir":"/tmp/nativefier-10-40-9-app--6218-MBz0aUcMHiV7","electronVersion":"13.6.3","name":"滴答清单","out":"/home/everyx/Downloads","overwrite":true,"platform":"linux","portable":false,"targetUrl":"https://dida365.com/signin","tmpdir":false,"upgrade":false,"win32metadata":{"ProductName":"滴答清单","InternalName":"滴答清单","FileDescription":"滴答清单"},"appBundleId":"com.electron.nativefier.滴答清单-nativefier-31f689"} +1ms
  electron-packager Target Platforms: linux +0ms
  electron-packager Target Architectures: x64 +0ms
  electron-packager Inferring appVersion from version in /tmp/nativefier-10-40-9-app--6218-MBz0aUcMHiV7/package.json +0ms
  electron-packager Application name: 滴答清单 +5ms
  electron-packager Target Electron version: 13.6.3 +0ms
  electron-packager Ignored path regular expressions: [
  '/package-lock\\.json$',
  '/yarn\\.lock$',
  '/\\.git($|/)',
  '/node_modules/\\.bin($|/)',
  '\\.o(bj)?$',
  '/tmp/electron-packager'
] +0ms
  electron-packager Downloading Electron with options {"platform":"linux","arch":"x64","version":"13.6.3","artifactName":"electron"} +0ms
Packaging app for platform linux x64 using electron v13.6.3
  electron-packager Creating /home/everyx/Downloads/linux-x64-template +4ms
  electron-packager Extracting /home/everyx/.cache/electron/1257abd35a3e246bfa6bbfdf499ffeaea4cbd1de726c24768a98684fb4cfb3c1/electron-v13.6.3-linux-x64.zip to /home/everyx/Downloads/linux-x64-template +0ms
  electron-packager Initializing app in /home/everyx/Downloads/滴答清单-linux-x64 from /home/everyx/Downloads/linux-x64-template template +0ms
  electron-packager Ignored paths based on the out param: [
  '/home/everyx/Downloads/滴答清单-darwin-x64',
  '/home/everyx/Downloads/滴答清单-darwin-arm64',
  '/home/everyx/Downloads/滴答清单-linux-ia32',
  '/home/everyx/Downloads/滴答清单-linux-x64',
  '/home/everyx/Downloads/滴答清单-linux-armv7l',
  '/home/everyx/Downloads/滴答清单-linux-arm64',
  '/home/everyx/Downloads/滴答清单-linux-mips64el',
  '/home/everyx/Downloads/滴答清单-mas-x64',
  '/home/everyx/Downloads/滴答清单-mas-arm64',
  '/home/everyx/Downloads/滴答清单-win32-ia32',
  '/home/everyx/Downloads/滴答清单-win32-x64',
  '/home/everyx/Downloads/滴答清单-win32-arm64'
] +2s
  electron-packager Validating bundled Electron app +0ms
  electron-packager Checking for a package.json file +0ms
  electron-packager Checking for the main entry point file +0ms
  electron-packager Validation complete +1ms
  electron-packager Renaming electron to 滴答清单 in /home/everyx/Downloads/滴答清单-linux-x64 +24ms

Finalizing build...
App built to /home/everyx/Downloads/滴答清单-linux-x64, move to wherever it makes sense for you and run the contained executable file (prefixing with ./ if necessary)
Menu/desktop shortcuts are up to you, because Nativefier cannot know where you're going to move the app. Search for "linux .desktop file" for help, or see https://wiki.archlinux.org/index.php/Desktop_entries
```

**Expected behavior**

What you expected to happen.

the app name should be "滴答清单-nativefier-xxxxx"

**Actual behavior**

![left of top bar of Gnome when app activated](https://user-images.githubusercontent.com/1665522/146626169-a312f89e-94c7-4752-a1fb-adce1eaf6f8f.png)

**Context**

 - Nativefier: 45.0.8
 - Node.js: v17.2.0
 - Npm: 8.2.0
 - OS: Arch Linux rolling
 - Is it a regression? Not sure
 - Additional context: DE is GNOME 41.2

**Comment by CuylerE** [comment]
Hi there, it seems like this is a locale-related issue - this seems to work on a Gnome-enabled Linux VM. You might have one of the language packages already installed on your machine, since I can see simplified chinese characters elsewhere -- but you may not have all of the locales properly enabled for Gnome. I'd recommend looking at both of these links to make sure you have every relevant locale package installed.

https://www.linuxquestions.org/questions/linux-software-2/display-chinese-in-gnome-306191/#post1557276
