### ISSUE TITLE
Downloading files from app

### ISSUE THREAD

**Issue by mcneds** [nativefier/nativefier#1383]
**Homework**

- [ye ] I looked at `nativefier --help` and https://github.com/nativefier/nativefier/blob/master/API.md
- [ye ] I checked the [Troubleshooting section of the README](https://github.com/nativefier/nativefier/blob/master/README.md#troubleshooting).
- [ ye] I searched existing issues, open & closed. Yes, my bug is new.
- [ ye] I'm using the latest version available at https://github.com/nativefier/nativefier/releases

**Bug description**
Idk if this is a bug or just something that doesnt exist, but when i click a button in the app to download a file nothing happens.

**Steps to reproduce**

literally try to download anything from  the app
BUILD LOGS:
```
PS C:\WINDOWS\system32> nativefier --verbose https://marian42.de/partdesigner/
Running in verbose mode! This will produce a mountain of logs and is recommended only for troubleshooting or if you like Shakespeare.


    Hi! Nativefier is minimally maintained these days, and needs more hands.
    If you have the time & motivation, help with bugfixes and maintenance is VERY welcome.
    Please go to https://github.com/nativefier/nativefier and help how you can. Thanks.



Processing options...
rawOptions {
  _: [ 'https://marian42.de/partdesigner/' ],
  verbose: true,
  c: false,
  conceal: false,
  'no-overwrite': false,
  noOverwrite: false,
  overwrite: true,
  portable: false,
  widevine: false,
  'always-on-top': false,
  alwaysOnTop: false,
  'disable-context-menu': false,
  disableContextMenu: false,
  'disable-dev-tools': false,
  disableDevTools: false,
  'full-screen': false,
  fullScreen: false,
  'hide-window-frame': false,
  hideWindowFrame: false,
  m: false,
  'show-menu-bar': false,
  showMenuBar: false,
  maximize: false,
  'single-instance': false,
  singleInstance: false,
  tray: 'false',
  zoom: 1,
  'user-agent-honest': false,
  honest: false,
  userAgentHonest: false,
  'clear-cache': false,
  clearCache: false,
  'block-external-urls': false,
  blockExternalUrls: false,
  'strict-internal-urls': false,
  strictInternalUrls: false,
  'disable-gpu': false,
  disableGpu: false,
  'enable-es3-apis': false,
  enableEs3Apis: false,
  'ignore-gpu-blacklist': false,
  ignoreGpuBlacklist: false,
  'disable-old-build-warning-yesiknowitisinsecure': false,
  disableOldBuildWarningYesiknowitisinsecure: false,
  'ignore-certificate': false,
  ignoreCertificate: false,
  insecure: false,
  flash: false,
  bounce: false,
  counter: false,
  'darwin-dark-mode-support': false,
  darwinDarkModeSupport: false,
  f: false,
  'fast-quit': false,
  fastQuit: false,
  quiet: false,
  '$0': 'nativefier',
  targetUrl: 'https://marian42.de/partdesigner/',
  out: undefined
}
Inferred arch x64
Normalized URL https://marian42.de/partdesigner/ to: https://marian42.de/partdesigner/
Running in verbose mode! This will produce a mountain of logs and is recommended only for troubleshooting or if you like Shakespeare.
Inferred platform win32

Performing async options post-processing.
Inferring icon for https://marian42.de/partdesigner/ on win32
Inferring icon from store for https://marian42.de/partdesigner/ on win32
Allowed icon formats when building for win32 (limited on Windows): [ '.ico' ]
Inferring name for https://marian42.de/partdesigner/
Fetched 9.9 kb page at https://marian42.de/partdesigner/
Inferred title: Part Designer
Sanitized filename for Part Designer : Part Designer
Got 246 icons from gitcloud
Max icon match score: 0
No relevant icon in store.
Trying to extract a .ico icon from the page.
Got an icon from the page.
Writing 1.5 kb icon to C:\Users\ak1di\AppData\Local\Temp\nativefier-18-53-32-iconinfer--19724-FOXDCV2kwp04\icon.png
options {
  packager: {
    appCopyright: undefined,
    appVersion: undefined,
    arch: 'x64',
    asar: false,
    buildVersion: undefined,
    darwinDarkModeSupport: false,
    dir: 'C:\\Users\\ak1di\\AppData\\Roaming\\npm\\node_modules\\nativefier\\app',
    electronVersion: '18.0.3',
    icon: 'C:\\Users\\ak1di\\AppData\\Local\\Temp\\nativefier-18-53-32-iconinfer--19724-FOXDCV2kwp04\\icon.png',
    name: 'Part Designer',
    out: 'C:\\WINDOWS\\system32',
    overwrite: true,
    quiet: false,
    platform: 'win32',
    portable: false,
    targetUrl: 'https://marian42.de/partdesigner/',
    tmpdir: false,
    upgrade: false,
    upgradeFrom: undefined,
    win32metadata: {
      ProductName: undefined,
      InternalName: undefined,
      FileDescription: undefined
    }
  },
  nativefier: {
    accessibilityPrompt: true,
    alwaysOnTop: false,
    backgroundColor: undefined,
    basicAuthPassword: undefined,
    basicAuthUsername: undefined,
    blockExternalUrls: false,
    bookmarksMenu: undefined,
    bounce: false,
    browserwindowOptions: undefined,
    clearCache: false,
    counter: false,
    crashReporter: undefined,
    disableContextMenu: false,
    disableDevTools: false,
    disableGpu: false,
    diskCacheSize: undefined,
    disableOldBuildWarning: false,
    enableEs3Apis: false,
    fastQuit: false,
    fileDownloadOptions: undefined,
    flashPluginDir: undefined,
    fullScreen: false,
    globalShortcuts: undefined,
    hideWindowFrame: false,
    ignoreCertificate: false,
    ignoreGpuBlacklist: false,
    inject: [],
    insecure: false,
    internalUrls: undefined,
    lang: undefined,
    maximize: false,
    nativefierVersion: '47.0.0',
    quiet: false,
    processEnvs: undefined,
    proxyRules: undefined,
    showMenuBar: false,
    singleInstance: false,
    strictInternalUrls: false,
    titleBarStyle: undefined,
    tray: 'false',
    userAgent: undefined,
    userAgentHonest: false,
    verbose: true,
    versionString: undefined,
    width: 1280,
    height: 800,
    minWidth: undefined,
    minHeight: undefined,
    maxWidth: undefined,
    maxHeight: undefined,
    widevine: false,
    x: undefined,
    y: undefined,
    zoom: 1
  }
}

Preparing Electron app...
Copying electron app from C:\Users\ak1di\AppData\Roaming\npm\node_modules\nativefier\app to C:\Users\ak1di\AppData\Local\Temp\nativefier-18-53-32-app--19724-01U4TYFm8a72
Writing app config to C:\Users\ak1di\AppData\Local\Temp\nativefier-18-53-32-app--19724-01U4TYFm8a72\nativefier.json {
  accessibilityPrompt: true,
  alwaysOnTop: false,
  appBundleId: undefined,
  appCategoryType: undefined,
  appCopyright: undefined,
  appVersion: undefined,
  arch: 'x64',
  asar: false,
  backgroundColor: undefined,
  basicAuthPassword: undefined,
  basicAuthUsername: undefined,
  blockExternalUrls: false,
  bounce: false,
  browserwindowOptions: undefined,
  buildDate: 1649642014042,
  buildVersion: undefined,
  clearCache: false,
  counter: false,
  crashReporter: undefined,
  darwinDarkModeSupport: false,
  derefSymlinks: undefined,
  disableContextMenu: false,
  disableDevTools: false,
  disableGpu: false,
  disableOldBuildWarning: false,
  diskCacheSize: undefined,
  download: undefined,
  electronVersionUsed: '18.0.3',
  enableEs3Apis: false,
  executableName: undefined,
  fastQuit: false,
  fileDownloadOptions: undefined,
  flashPluginDir: undefined,
  fullScreen: false,
  globalShortcuts: undefined,
  height: 800,
  helperBundleId: undefined,
  hideWindowFrame: false,
  ignoreCertificate: false,
  ignoreGpuBlacklist: false,
  insecure: false,
  internalUrls: undefined,
  isUpgrade: false,
  junk: undefined,
  lang: undefined,
  maximize: false,
  maxHeight: undefined,
  maxWidth: undefined,
  minHeight: undefined,
  minWidth: undefined,
  name: 'Part Designer',
  nativefierVersion: '47.0.0',
  osxNotarize: undefined,
  osxSign: undefined,
  portable: false,
  processEnvs: undefined,
  protocols: undefined,
  proxyRules: undefined,
  prune: undefined,
  quiet: false,
  showMenuBar: false,
  singleInstance: false,
  strictInternalUrls: false,
  targetUrl: 'https://marian42.de/partdesigner/',
  titleBarStyle: undefined,
  tray: 'false',
  usageDescription: undefined,
  userAgent: undefined,
  userAgentHonest: false,
  versionString: undefined,
  width: 1280,
  widevine: false,
  win32metadata: {
    ProductName: undefined,
    InternalName: undefined,
    FileDescription: undefined
  },
  x: undefined,
  y: undefined,
  zoom: 1,
  oldBuildWarningText: ''
}
No files to inject, skipping copy.
Updating C:\Users\ak1di\AppData\Local\Temp\nativefier-18-53-32-app--19724-01U4TYFm8a72\package.json 'name' field to part-designer-nativefier-29a2db

Converting icons...
Failed to convert icon to .ico, skipping. Error: Icon conversion only supported on macOS or Linux. If building for Windows, download/create a .ico and pass it with --icon favicon.ico . If building for macOS/Linux, do it from macOS/Linux
    at iconShellHelper (C:\Users\ak1di\AppData\Roaming\npm\node_modules\nativefier\src\helpers\iconShellHelpers.ts:28:11)
    at convertToIco (C:\Users\ak1di\AppData\Roaming\npm\node_modules\nativefier\src\helpers\iconShellHelpers.ts:71:10)
    at convertIconIfNecessary (C:\Users\ak1di\AppData\Roaming\npm\node_modules\nativefier\src\build\buildIcon.ts:45:36)
    at buildNativefierApp (C:\Users\ak1di\AppData\Roaming\npm\node_modules\nativefier\src\build\buildNativefierApp.ts:190:25)
Copying icons if necessary
Copying icon C:\Users\ak1di\AppData\Local\Temp\nativefier-18-53-32-iconinfer--19724-FOXDCV2kwp04\icon.png to C:\Users\ak1di\AppData\Local\Temp\nativefier-18-53-32-app--19724-01U4TYFm8a72\icon.png

Packaging... This will take a few seconds, maybe minutes if the requested Electron isn't cached yet...
  electron-packager Electron Packager 15.4.0
  electron-packager Node v16.14.2
  electron-packager Host Operating system: win32 10.0.19043 (x64) +0ms
  electron-packager Packager Options: {"arch":"x64","asar":false,"darwinDarkModeSupport":false,"dir":"C:\\Users\\ak1di\\AppData\\Local\\Temp\\nativefier-18-53-32-app--19724-01U4TYFm8a72","electronVersion":"18.0.3","icon":"C:\\Users\\ak1di\\AppData\\Local\\Temp\\nativefier-18-53-32-iconinfer--19724-FOXDCV2kwp04\\icon.png","name":"Part Designer","out":"C:\\WINDOWS\\system32","overwrite":true,"quiet":false,"platform":"win32","portable":false,"targetUrl":"https://marian42.de/partdesigner/","tmpdir":false,"upgrade":false,"win32metadata":{},"appBundleId":"com.electron.nativefier.part-designer-nativefier-29a2db"} +0ms
  electron-packager Target Platforms: win32 +2ms
  electron-packager Target Architectures: x64 +0ms
  electron-packager Requiring author in package.json, as CompanyName was not specified for win32metadata +0ms
  electron-packager Inferring appVersion from version in C:\Users\ak1di\AppData\Local\Temp\nativefier-18-53-32-app--19724-01U4TYFm8a72\package.json +4ms
  electron-packager Inferring win32metadata.CompanyName from author in C:\Users\ak1di\AppData\Local\Temp\nativefier-18-53-32-app--19724-01U4TYFm8a72\package.json +0ms
  electron-packager Application name: Part Designer +5ms
  electron-packager Target Electron version: 18.0.3 +1ms
  electron-packager Ignored path regular expressions: [
  '/package-lock\\.json$',
  '/yarn\\.lock$',
  '/\\.git($|/)',
  '/node_modules/\\.bin($|/)',
  '\\.o(bj)?$'
] +0ms
  electron-packager Downloading Electron with options {"platform":"win32","arch":"x64","version":"18.0.3","artifactName":"electron"} +0ms
Packaging app for platform win32 x64 using electron v18.0.3
  electron-packager Creating C:\WINDOWS\system32\win32-x64-template +4ms
  electron-packager Extracting C:\Users\ak1di\AppData\Local\electron\Cache\f4b53fda321adc66035985eac16777325dc589e9f8d2c60f8a36c64dccc7a9c0\electron-v18.0.3-win32-x64.zip to C:\WINDOWS\system32\win32-x64-template +1ms
  electron-packager Initializing app in C:\WINDOWS\system32\Part Designer-win32-x64 from C:\WINDOWS\system32\win32-x64-template template +0ms
  electron-packager Ignored paths based on the out param: [
  'C:\\WINDOWS\\system32\\Part Designer-darwin-x64',
  'C:\\WINDOWS\\system32\\Part Designer-darwin-arm64',
  'C:\\WINDOWS\\system32\\Part Designer-linux-ia32',
  'C:\\WINDOWS\\system32\\Part Designer-linux-x64',
  'C:\\WINDOWS\\system32\\Part Designer-linux-armv7l',
  'C:\\WINDOWS\\system32\\Part Designer-linux-arm64',
  'C:\\WINDOWS\\system32\\Part Designer-linux-mips64el',
  'C:\\WINDOWS\\system32\\Part Designer-mas-x64',
  'C:\\WINDOWS\\system32\\Part Designer-mas-arm64',
  'C:\\WINDOWS\\system32\\Part Designer-win32-ia32',
  'C:\\WINDOWS\\system32\\Part Designer-win32-x64',
  'C:\\WINDOWS\\system32\\Part Designer-win32-arm64'
] +1s
  electron-packager Validating bundled Electron app +0ms
  electron-packager Checking for a package.json file +0ms
  electron-packager Checking for the main entry point file +1ms
  electron-packager Validation complete +1ms
  electron-packager Renaming electron.exe to Part Designer.exe in C:\WINDOWS\system32\Part Designer-win32-x64 +24ms
WARNING: Could not find icon "C:\Users\ak1di\AppData\Local\Temp\nativefier-18-53-32-iconinfer--19724-FOXDCV2kwp04\icon.ico", not updating app icon
  electron-packager Running rcedit with the options {"version-string":{"OriginalFilename":"Part Designer.exe","CompanyName":"Jia Hao"},"file-version":"1.0.0","product-version":"1.0.0"} +0ms

Finalizing build...
App built to C:\WINDOWS\system32\Part Designer-win32-x64, move to wherever it makes sense for you and run the contained .exe file.

```

**Expected behavior**

a file to be downloaded, and file explorer to open

**Actual behavior**

nothing

**Debug info**

https://www.kapwing.com/videos/62538b79e312790065bc01bb
video of it working in chrome (screen changes hue it just didnt record file explorer opening) and not working in the app built from nativefier

**Context**

 - Nativefier: latest
 - Node.js: latest
 - Npm: latest

**Comment by ronjouch** [comment]
Downloading does happen, it's just sadly extremely non-obvious. Closing as dup of #335

**Comment by mcneds** [comment]
> Downloading does happen, it's just sadly extremely non-obvious. Closing as dup of #335

So where does it download to, if file explorer doesn't pop up?

**Comment by ronjouch** [comment]
It depends on your OS. Read #335 please.
