### ISSUE TITLE
Error: EEXIST: file already exists, symlink 'Versions/Current/Electron Framework' -> '/Users/ravi/darwin-x64-template/Electron.app/Contents/Frameworks/Electron Framework.framework/Electron Framework'

### ISSUE THREAD

**Issue by msr8** [nativefier/nativefier#1431]
**Homework**

- [x] I looked at `nativefier --help` and https://github.com/nativefier/nativefier/blob/master/API.md
- [x] I searched existing issues, open & closed. Yes, my question is new.
- [x] I'm using the latest version available at https://github.com/nativefier/nativefier/releases

**Your question**

Cannot build the spotify app for some reason, gives me the error `EEXIST: file already exists, symlink 'Versions/Current/Electron Framework' -> '/Users/ravi/darwin-x64-template/Electron.app/Contents/Frameworks/Electron Framework.framework/Electron Framework'`. Full logs are given below

**Steps to reproduce**

```
 ╰─[$] nativefier --verbose https://open.spotify.com/
Running in verbose mode! This will produce a mountain of logs and is recommended only for troubleshooting or if you like Shakespeare.


    Hi! Nativefier is minimally maintained these days, and needs more hands.
    If you have the time & motivation, help with bugfixes and maintenance is VERY welcome.
    Please go to https://github.com/nativefier/nativefier and help how you can. Thanks.



Processing options...
rawOptions {
  _: [ 'https://open.spotify.com/' ],
  verbose: true,
  c: false,
  conceal: false,
  'no-overwrite': false,
  noOverwrite: false,
  overwrite: true,
  portable: false,
  widevine: false,
  'always-on-top': false,
  alwaysOnTop: false,
  'disable-context-menu': false,
  disableContextMenu: false,
  'disable-dev-tools': false,
  disableDevTools: false,
  'full-screen': false,
  fullScreen: false,
  'hide-window-frame': false,
  hideWindowFrame: false,
  m: false,
  'show-menu-bar': false,
  showMenuBar: false,
  maximize: false,
  'single-instance': false,
  singleInstance: false,
  tray: 'false',
  zoom: 1,
  'user-agent-honest': false,
  honest: false,
  userAgentHonest: false,
  'clear-cache': false,
  clearCache: false,
  'block-external-urls': false,
  blockExternalUrls: false,
  'strict-internal-urls': false,
  strictInternalUrls: false,
  'disable-gpu': false,
  disableGpu: false,
  'enable-es3-apis': false,
  enableEs3Apis: false,
  'ignore-gpu-blacklist': false,
  ignoreGpuBlacklist: false,
  'disable-old-build-warning-yesiknowitisinsecure': false,
  disableOldBuildWarningYesiknowitisinsecure: false,
  'ignore-certificate': false,
  ignoreCertificate: false,
  insecure: false,
  flash: false,
  bounce: false,
  counter: false,
  'darwin-dark-mode-support': false,
  darwinDarkModeSupport: false,
  f: false,
  'fast-quit': false,
  fastQuit: false,
  quiet: false,
  '$0': 'nativefier',
  targetUrl: 'https://open.spotify.com/',
  out: undefined
}
Inferred arch x64
Normalized URL https://open.spotify.com/ to: https://open.spotify.com/
Running in verbose mode! This will produce a mountain of logs and is recommended only for troubleshooting or if you like Shakespeare.
Inferred platform darwin

Performing async options post-processing.
Inferring icon for https://open.spotify.com/ on darwin
Inferring icon from store for https://open.spotify.com/ on darwin
Allowed icon formats when building for darwin: [ '.icns', '.png', '.ico' ]
Inferring name for https://open.spotify.com/
Fetched 7.8 kb page at https://open.spotify.com/
Inferred title: Spotify - Web Player: Music for everyone
Sanitized filename for Spotify - Web Player: Music for everyone : Spotify - Web Player Music for everyone
Got 246 icons from gitcloud
Max icon match score: 0
No relevant icon in store.
Trying to extract a .png icon from the page.
Got an icon from the page.
Writing 249.1 kb icon to /var/folders/c9/m20q14596259rrvt9bsxrpq40000gn/T/nativefier-13-18-12-iconinfer--8096-fckacYbdWvoa/icon.png
options {
  packager: {
    appCopyright: undefined,
    appVersion: undefined,
    arch: 'x64',
    asar: false,
    buildVersion: undefined,
    darwinDarkModeSupport: false,
    dir: '/usr/local/lib/node_modules/nativefier/app',
    electronVersion: '18.3.5',
    icon: '/var/folders/c9/m20q14596259rrvt9bsxrpq40000gn/T/nativefier-13-18-12-iconinfer--8096-fckacYbdWvoa/icon.png',
    name: 'Spotify - Web Player Music for everyone',
    out: '/Users/ravi',
    overwrite: true,
    quiet: false,
    platform: 'darwin',
    portable: false,
    targetUrl: 'https://open.spotify.com/',
    tmpdir: false,
    upgrade: false,
    upgradeFrom: undefined,
    win32metadata: {
      ProductName: undefined,
      InternalName: undefined,
      FileDescription: undefined
    }
  },
  nativefier: {
    accessibilityPrompt: true,
    alwaysOnTop: false,
    backgroundColor: undefined,
    basicAuthPassword: undefined,
    basicAuthUsername: undefined,
    blockExternalUrls: false,
    bookmarksMenu: undefined,
    bounce: false,
    browserwindowOptions: undefined,
    clearCache: false,
    counter: false,
    crashReporter: undefined,
    disableContextMenu: false,
    disableDevTools: false,
    disableGpu: false,
    diskCacheSize: undefined,
    disableOldBuildWarning: false,
    enableEs3Apis: false,
    fastQuit: false,
    fileDownloadOptions: undefined,
    flashPluginDir: undefined,
    fullScreen: false,
    globalShortcuts: undefined,
    hideWindowFrame: false,
    ignoreCertificate: false,
    ignoreGpuBlacklist: false,
    inject: [],
    insecure: false,
    internalUrls: undefined,
    lang: undefined,
    maximize: false,
    nativefierVersion: '47.2.1',
    quiet: false,
    processEnvs: undefined,
    proxyRules: undefined,
    showMenuBar: false,
    singleInstance: false,
    strictInternalUrls: false,
    titleBarStyle: undefined,
    tray: 'false',
    userAgent: undefined,
    userAgentHonest: false,
    verbose: true,
    versionString: undefined,
    width: 1280,
    height: 800,
    minWidth: undefined,
    minHeight: undefined,
    maxWidth: undefined,
    maxHeight: undefined,
    widevine: false,
    x: undefined,
    y: undefined,
    zoom: 1
  }
}

Preparing Electron app...
Copying electron app from /usr/local/lib/node_modules/nativefier/app to /var/folders/c9/m20q14596259rrvt9bsxrpq40000gn/T/nativefier-13-18-12-app--8096-ZYPQjeqMgnna
Writing app config to /var/folders/c9/m20q14596259rrvt9bsxrpq40000gn/T/nativefier-13-18-12-app--8096-ZYPQjeqMgnna/nativefier.json {
  accessibilityPrompt: true,
  alwaysOnTop: false,
  appBundleId: undefined,
  appCategoryType: undefined,
  appCopyright: undefined,
  appVersion: undefined,
  arch: 'x64',
  asar: false,
  backgroundColor: undefined,
  basicAuthPassword: undefined,
  basicAuthUsername: undefined,
  blockExternalUrls: false,
  bounce: false,
  browserwindowOptions: undefined,
  buildDate: 1657007295286,
  buildVersion: undefined,
  clearCache: false,
  counter: false,
  crashReporter: undefined,
  darwinDarkModeSupport: false,
  derefSymlinks: undefined,
  disableContextMenu: false,
  disableDevTools: false,
  disableGpu: false,
  disableOldBuildWarning: false,
  diskCacheSize: undefined,
  download: undefined,
  electronVersionUsed: '18.3.5',
  enableEs3Apis: false,
  executableName: undefined,
  fastQuit: false,
  fileDownloadOptions: undefined,
  flashPluginDir: undefined,
  fullScreen: false,
  globalShortcuts: undefined,
  height: 800,
  helperBundleId: undefined,
  hideWindowFrame: false,
  ignoreCertificate: false,
  ignoreGpuBlacklist: false,
  insecure: false,
  internalUrls: undefined,
  isUpgrade: false,
  junk: undefined,
  lang: undefined,
  maximize: false,
  maxHeight: undefined,
  maxWidth: undefined,
  minHeight: undefined,
  minWidth: undefined,
  name: 'Spotify - Web Player Music for everyone',
  nativefierVersion: '47.2.1',
  osxNotarize: undefined,
  osxSign: undefined,
  portable: false,
  processEnvs: undefined,
  protocols: undefined,
  proxyRules: undefined,
  prune: undefined,
  quiet: false,
  showMenuBar: false,
  singleInstance: false,
  strictInternalUrls: false,
  targetUrl: 'https://open.spotify.com/',
  titleBarStyle: undefined,
  tray: 'false',
  usageDescription: undefined,
  userAgent: undefined,
  userAgentHonest: false,
  versionString: undefined,
  width: 1280,
  widevine: false,
  win32metadata: {
    ProductName: undefined,
    InternalName: undefined,
    FileDescription: undefined
  },
  x: undefined,
  y: undefined,
  zoom: 1,
  oldBuildWarningText: ''
}
No files to inject, skipping copy.
Updating /var/folders/c9/m20q14596259rrvt9bsxrpq40000gn/T/nativefier-13-18-12-app--8096-ZYPQjeqMgnna/package.json 'name' field to spotify---web-player-music-for-everyone-nativefier-437e3b

Converting icons...
Converting icon /var/folders/c9/m20q14596259rrvt9bsxrpq40000gn/T/nativefier-13-18-12-iconinfer--8096-fckacYbdWvoa/icon.png to /var/folders/c9/m20q14596259rrvt9bsxrpq40000gn/T/nativefier-13-18-12-iconconv--8096-zvweh05OgQ49/icon.icns. Calling shell command: "/usr/local/lib/node_modules/nativefier/icon-scripts/convertToIcns" "/var/folders/c9/m20q14596259rrvt9bsxrpq40000gn/T/nativefier-13-18-12-iconinfer--8096-fckacYbdWvoa/icon.png" "/var/folders/c9/m20q14596259rrvt9bsxrpq40000gn/T/nativefier-13-18-12-iconconv--8096-zvweh05OgQ49/icon.icns"
Failed to convert icon to .icns, skipping. Error: Icon conversion failed with status code 1.
stdout: 
stderr: /var/folders/c9/m20q14596259rrvt9bsxrpq40000gn/T/nativefier-icns-XXXXXX.9I0BLcKh/converted.iconset:Failed to generate ICNS.

    at iconShellHelper (/usr/local/lib/node_modules/nativefier/src/helpers/iconShellHelpers.ts:46:11)
    at convertToIcns (/usr/local/lib/node_modules/nativefier/src/helpers/iconShellHelpers.ts:83:10)
    at convertIconIfNecessary (/usr/local/lib/node_modules/nativefier/src/build/buildIcon.ts:87:37)
    at buildNativefierApp (/usr/local/lib/node_modules/nativefier/src/build/buildNativefierApp.ts:219:25)
Copying icons if necessary
No icon specified in options; aborting

Packaging... This will take a few seconds, maybe minutes if the requested Electron isn't cached yet...
  electron-packager Electron Packager 15.5.1
  electron-packager Node v18.3.0
  electron-packager Host Operating system: darwin 19.2.0 (x64) +0ms
  electron-packager Packager Options: {"arch":"x64","asar":false,"darwinDarkModeSupport":false,"dir":"/var/folders/c9/m20q14596259rrvt9bsxrpq40000gn/T/nativefier-13-18-12-app--8096-ZYPQjeqMgnna","electronVersion":"18.3.5","name":"Spotify - Web Player Music for everyone","out":"/Users/ravi","overwrite":true,"quiet":false,"platform":"darwin","portable":false,"targetUrl":"https://open.spotify.com/","tmpdir":false,"upgrade":false,"win32metadata":{},"appBundleId":"com.electron.nativefier.spotify---web-player-music-for-everyone-nativefier-437e3b"} +0ms
  electron-packager Target Platforms: darwin +1ms
  electron-packager Target Architectures: x64 +0ms
  electron-packager Inferring appVersion from version in /var/folders/c9/m20q14596259rrvt9bsxrpq40000gn/T/nativefier-13-18-12-app--8096-ZYPQjeqMgnna/package.json +0ms
  electron-packager Application name: Spotify - Web Player Music for everyone +10ms
  electron-packager Target Electron version: 18.3.5 +0ms
  electron-packager Ignored path regular expressions: [
  '/package-lock\\.json$',
  '/yarn\\.lock$',
  '/\\.git($|/)',
  '/node_modules/\\.bin($|/)',
  '\\.o(bj)?$'
] +0ms
  electron-packager Downloading Electron with options {"platform":"darwin","arch":"x64","version":"18.3.5","artifactName":"electron"} +0ms
Packaging app for platform darwin x64 using electron v18.3.5
  electron-packager Creating /Users/ravi/darwin-x64-template +3ms
  electron-packager Extracting /Users/ravi/Library/Caches/electron/6e2b7866abc5ebab695766afaa24f30771713bad68e1b6cf6e9f4230559275af/electron-v18.3.5-darwin-x64.zip to /Users/ravi/darwin-x64-template +1ms
Error during build. Run with --verbose for details. [Error: EEXIST: file already exists, symlink 'Versions/Current/Electron Framework' -> '/Users/ravi/darwin-x64-template/Electron.app/Contents/Frameworks/Electron Framework.framework/Electron Framework'] {
  errno: -17,
  code: 'EEXIST',
  syscall: 'symlink',
  path: 'Versions/Current/Electron Framework',
  dest: '/Users/ravi/darwin-x64-template/Electron.app/Contents/Frameworks/Electron Framework.framework/Electron Framework'
}
```

**Context**

 - Nativefier: 47.2.1
 - Node.js: Dont know how to view ¯\\\_(ツ)\\_/¯
 - Npm: 8.13.2
 - OS: MacOS 10.15.2 Catalina
 - Additional context:
![Screenshot 2022-07-05 at 13 23 02](https://user-images.githubusercontent.com/79649185/177278191-29ae189e-0560-43e9-9be0-8b961e17f52d.png)

**Comment by msr8** [comment]
Fixed it by deleting `/Users/ravi/darwin-x64-template`
