### ISSUE TITLE
run on win10, error

### ISSUE THREAD

**Issue by hktalent** [nativefier/nativefier#1540]
### Homework

- [X] I took the time to write a good, descriptive issue title
- [X] I read `nativefier --help` and [API.md](https://github.com/nativefier/nativefier/blob/master/API.md).
- [X] I checked [CATALOG.md](https://github.com/nativefier/nativefier/blob/master/CATALOG.md) for community suggestions & workarounds.
- [X] I searched [existing issues, open & closed](https://github.com/nativefier/nativefier/issues?q=is%3Aissue). Yes, my bug is new.
- [X] I'm running the [latest version](https://github.com/nativefier/nativefier/releases).

### Nativefier command

nativefier --name "ocr app" "https://127.0.0.1:8080"

### Steps to reproduce

npm install -g nativefier@latest
nativefier --name "ocr app" "https://127.0.0.1:8080"

### Expected behavior

error

### Actual behavior

error

### Debug info

```
Running in verbose mode! This will produce a mountain of logs and is recommended only for troubleshooting or if you like Shakespeare.


    Hi! Nativefier is minimally maintained these days, and needs more hands.
    If you have the time & motivation, help with bugfixes and maintenance is VERY welcome.
    Please go to https://github.com/nativefier/nativefier and help how you can. Thanks.



Processing options...
rawOptions {
  _: [ 'https://127.0.0.1:8080' ],
  name: 'ocr app',
  n: 'ocr app',
  verbose: true,
  c: false,
  conceal: false,
  'no-overwrite': false,
  noOverwrite: false,
  overwrite: true,
  portable: false,
  widevine: false,
  'always-on-top': false,
  alwaysOnTop: false,
  'disable-context-menu': false,
  disableContextMenu: false,
  'disable-dev-tools': false,
  disableDevTools: false,
  'full-screen': false,
  fullScreen: false,
  'hide-window-frame': false,
  hideWindowFrame: false,
  m: false,
  'show-menu-bar': false,
  showMenuBar: false,
  maximize: false,
  'single-instance': false,
  singleInstance: false,
  tray: 'false',
  zoom: 1,
  'user-agent-honest': false,
  honest: false,
  userAgentHonest: false,
  'clear-cache': false,
  clearCache: false,
  'block-external-urls': false,
  blockExternalUrls: false,
  'strict-internal-urls': false,
  strictInternalUrls: false,
  'disable-gpu': false,
  disableGpu: false,
  'enable-es3-apis': false,
  enableEs3Apis: false,
  'ignore-gpu-blacklist': false,
  ignoreGpuBlacklist: false,
  'disable-old-build-warning-yesiknowitisinsecure': false,
  disableOldBuildWarningYesiknowitisinsecure: false,
  'ignore-certificate': false,
  ignoreCertificate: false,
  insecure: false,
  flash: false,
  bounce: false,
  counter: false,
  'darwin-dark-mode-support': false,
  darwinDarkModeSupport: false,
  f: false,
  'fast-quit': false,
  fastQuit: false,
  quiet: false,
  '$0': 'nativefier',
  targetUrl: 'https://127.0.0.1:8080',
  out: undefined
}
Error during build. Run with --verbose for details. Error: Incompatible architecture ia32 detected
    at inferArch (C:\Users\xiatian\AppData\Roaming\npm\node_modules\nativefier\src\infer\inferOs.ts:31:11)
    at getOptions (C:\Users\xiatian\AppData\Roaming\npm\node_modules\nativefier\src\options\optionsMain.ts:41:41)
    at buildNativefierApp (C:\Users\xiatian\AppData\Roaming\npm\node_modules\nativefier\src\build\buildNativefierApp.ts:176:35)
    at Object.<anonymous> (C:\Users\xiatian\AppData\Roaming\npm\node_modules\nativefier\src\cli.ts:702:21)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Function.Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

```

### Nativefier version

50.1.1

### Node.js version

v18.16.1

### npm version

9.7.2

### OS

windows 10

**Comment by admin-elvistrujanovic** [comment]
The same bug has happened again on Windows 10 (x64), npm version 9.8.0 and node version: v20.4.0
