### ISSUE TITLE
The bug from #1540 is again active

### ISSUE THREAD

**Issue by admin-elvistrujanovic** [nativefier/nativefier#1545]
### Homework

- [X] I took the time to write a good, descriptive issue title
- [X] I read `nativefier --help` and [API.md](https://github.com/nativefier/nativefier/blob/master/API.md).
- [X] I checked [CATALOG.md](https://github.com/nativefier/nativefier/blob/master/CATALOG.md) for community suggestions & workarounds.
- [X] I searched [existing issues, open & closed](https://github.com/nativefier/nativefier/issues?q=is%3Aissue). Yes, my bug is new.
- [X] I'm running the [latest version](https://github.com/nativefier/nativefier/releases).

### Nativefier command

nativefier "YouTube" "https://www.youtube.com" --verbose

### Steps to reproduce

1. First, I installed the software using nodejs via this command: npm install -g nativefier@latest
2. After that I executed the next command to create the app
3. Error

### Expected behavior

Normal building (creating) the app

### Actual behavior

Architecture error bug.

### Debug info

Running in verbose mode! This will produce a mountain of logs and is recommended only for troubleshooting or if you like Shakespeare.

    Hi! Nativefier is minimally maintained these days, and needs more hands.
    If you have the time & motivation, help with bugfixes and maintenance is VERY welcome.
    Please go to https://github.com/nativefier/nativefier and help how you can. Thanks.

Processing options...
rawOptions {
  _: [ 'https://www.youtube.com' ],
  name: 'YouTube',
  n: 'YouTube',
  verbose: true,
  c: false,
  conceal: false,
  'no-overwrite': false,
  noOverwrite: false,
  overwrite: true,
  portable: false,
  widevine: false,
  'always-on-top': false,
  alwaysOnTop: false,
  'disable-context-menu': false,
  disableContextMenu: false,
  'disable-dev-tools': false,
  disableDevTools: false,
  'full-screen': false,
  fullScreen: false,
  'hide-window-frame': false,
  hideWindowFrame: false,
  m: false,
  'show-menu-bar': false,
  showMenuBar: false,
  maximize: false,
  'single-instance': false,
  singleInstance: false,
  tray: 'false',
  zoom: 1,
  'user-agent-honest': false,
  honest: false,
  userAgentHonest: false,
  'clear-cache': false,
  clearCache: false,
  'block-external-urls': false,
  blockExternalUrls: false,
  'strict-internal-urls': false,
  strictInternalUrls: false,
  'disable-gpu': false,
  disableGpu: false,
  'enable-es3-apis': false,
  enableEs3Apis: false,
  'ignore-gpu-blacklist': false,
  ignoreGpuBlacklist: false,
  'disable-old-build-warning-yesiknowitisinsecure': false,
  disableOldBuildWarningYesiknowitisinsecure: false,
  'ignore-certificate': false,
  ignoreCertificate: false,
  insecure: false,
  flash: false,
  bounce: false,
  counter: false,
  'darwin-dark-mode-support': false,
  darwinDarkModeSupport: false,
  f: false,
  'fast-quit': false,
  fastQuit: false,
  quiet: false,
  '$0': 'nativefier',
  targetUrl: 'https://www.youtube.com',
  out: undefined
}
Error during build. Run with --verbose for details. Error: Incompatible architecture ia32 detected
    at inferArch (C:\Users\xiatian\AppData\Roaming\npm\node_modules\nativefier\src\infer\inferOs.ts:31:11)
    at getOptions (C:\Users\xiatian\AppData\Roaming\npm\node_modules\nativefier\src\options\optionsMain.ts:41:41)
    at buildNativefierApp (C:\Users\xiatian\AppData\Roaming\npm\node_modules\nativefier\src\build\buildNativefierApp.ts:176:35)
    at Object.<anonymous> (C:\Users\xiatian\AppData\Roaming\npm\node_modules\nativefier\src\cli.ts:702:21)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Function.Module._load (node:internal/modules/cjs/loader:938:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47

### Nativefier version

50.1.1

### Node.js version

v20.4.0

### npm version

9.8.0

### OS

Windows 11 22H2 (OS Build 22621.1555)

**Comment by admin-elvistrujanovic** [comment]
Tag: #1540

**Comment by TheCleric** [comment]
Can you tell me what CPU you have? [https://www.howtogeek.com/413942/how-to-see-what-cpu-is-in-your-pc-and-how-fast-it-is/]()

Can you run the following and tell me what it outputs? `node -e "console.log(process.arch)"`

**Comment by admin-elvistrujanovic** [comment]
> Can you tell me what CPU you have? [https://www.howtogeek.com/413942/how-to-see-what-cpu-is-in-your-pc-and-how-fast-it-is/]()
> 
> Can you run the following and tell me what it outputs? `node -e "console.log(process.arch)"`

x86_64
