### ISSUE TITLE
Can't build windows apps using docker

### ISSUE THREAD

**Issue by inclooder** [nativefier/nativefier#997]
**Bug description**
nativefier is failing to build windows app.

**Steps to reproduce**
`docker build -t local/nativefier .`
`docker run --rm -v $(pwd):/target local/nativefier -p windows http://google.com /target/`

**Expected behavior**
Successful build

**Actual behavior**
Failed build

**Debug info**
```
Preparing Electron app...

Converting icons...

Packaging... This will take a few seconds, maybe minutes if the requested Electron isn't cached yet...
Packaging app for platform win32 x64 using electron v9.0.4
Error during build. Run with --verbose for details. Error: Could not find "wine64" on your system.

Wine is required to use the appCopyright, appVersion, buildVersion, icon, and 
win32metadata parameters for Windows targets.

Make sure that the "wine64" executable is in your PATH.

See https://github.com/electron/electron-packager#building-windows-apps-from-non-windows-platforms for details.
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn wine64',
  path: 'wine64',
  spawnargs: [
    '/nativefier/node_modules/rcedit/bin/rcedit-x64.exe',
    '/target/Google-win32-x64/Google.exe',
    '--set-version-string',
    'FileDescription',
    [Function],
    '--set-version-string',
    'InternalName',
    [Function],
    '--set-version-string',
    'OriginalFilename',
    'Google.exe',
    '--set-version-string',
    'ProductName',
    [Function],
    '--set-version-string',
    'CompanyName',
    'Jia Hao',
    '--set-file-version',
    '1.0.0',
    '--set-product-version',
    '1.0.0',
    '--set-icon',
    '/tmp/nativefier-18-10-25-iconconv--1-P43AEb8JRRah/icon.ico'
  ]
}
```

**Context**
 - Nativefier: 9.0.0
 - OS: (arch linux)

**Comment by gruessung** [comment]
+1
